// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export type AdDTO = {
  _id: string;
  description: string;
  title?: string;
  subtitle?: string;
  contact?: string;
  phone?: string;
  delivery?: boolean;
  email?: string;
  address?: string;
  neighborhood?: string;
  city?: string;
  link?: string;
  qrCode?: string;
  adFormatId: string;
  urls: string[];
  order: {
    x: number;
    y: number;
  };
};

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<AdDTO[]>
) {
  if (req.method === "PUT") {
    console.log(JSON.parse(req.body));
  }

  if (req.method === "POST") {
    res.status(201).json({} as AdDTO[]);
    return;
  }

  res.status(200).json([
    {
      _id: "620ace6313589700166baf4f",
      description:
        "HARMONIZAÇÃO FACIAL | BOTOX | PREENCHIMENTO LABIAL | BIOESTIMULADORES | FIOS DE SUSTENTAÇÃO",
      title: "VANESSA BIAZUTTI",
      subtitle: "biomédica esteta",
      contact: "Vanessa Biazutti",
      phone: "::::99938-2448",
      delivery: false,
      email: "ig:@Vanessa_Biazutti",
      address: "Rua Domingos Henriques de Gusmão, 56 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/vanessaBiazutti.png"],
      order: { x: 0, y: 1 },
    },
    {
      _id: "61b92ca6ff15c00016366596",
      description: "",
      title: "CASA DE CARNES SANTA RITA",
      subtitle: "O MELHOR PARA VOCÊ",
      contact: "AOS DOMINGOS FRANGO E CARNE ASSADA",
      phone: ":::32:3261-1952/wa::::99918-5852",
      delivery: false,
      email: "",
      address: "Rua Duque de Caxias, 49 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/casaDeCarnesSantaRita.png"],
      order: { x: 0, y: 2 },
    },
    {
      _id: "620ace6313589700166baf4z",
      description:
        "CEREAIS, BEBIDAS EM GERAL | FRANGO INTEIRO E PEDAÇO, GÁS O MELHOR PREÇO | ENTREGAMOS: GÁS E COMPRAS",
      title: "Chave de Ouro",
      subtitle: "Bar e Mercearia",
      contact: "Sebastião Rosa",
      phone: "::::99937-3616",
      delivery: false,
      email: "",
      address: "Rua Capitão Ferreira Campos, 93 - saída para Descoberto",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/barMerceariaChaveDeOuro.png"],
      order: { x: 6, y: 2 },
    },
    {
      _id: "620ace6313589700166baf4l",
      description:
        "PNEUS, BATERIAS, TROCA DE ÓLEO E AUTO PEÇAS - BORRACHARIA COMPLETA | SUPER TROCA DE ÓLEO | LUBRIFICANTE CARRO E MOTO",
      title: "GOLDIN",
      subtitle: "Tudo para o seu carro e moto",
      contact: "Disk",
      phone: "::::99838-7473",
      delivery: false,
      email: "",
      address: "Rua Cônego Reis, 256 - Centro",
      neighborhood: "Centro",
      city: "SÃO JOÃO NEPOMUCENO - MG - PRÓXIMO DE VOCÊ",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/goldinPneus.png"],
      order: { x: 0, y: 3 },
    },
    {
      _id: "60f603e2557aac0015cca542",
      description:
        "com teste do sistema de injeção com Aparelho Raster - equipamento de análise e limpeza de injetores de combustivel | VENDAS DE BATERIAS, SILENCIOSO, TROCA DE ÓLEO E PEÇAS EM GERAL | Serviços em carros nacional e importado | atendimento 24 horas",
      title: "MECÂNICA E LOJA CARNEIRINHO",
      subtitle: "MECÂNICA EM GERAL",
      contact: "",
      phone: ":::32:3261-4079/::::99965-5864",
      delivery: false,
      email: "",
      address: "Av. Celso Cosme de Castro, 1385 - Chácara dos Palmares",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/mecanicaCarneirinho.png"],
      order: { x: 0, y: 5 },
    },
    {
      _id: "61f603e2557aac0015cca542",
      description:
        "Serviços Oferecidos: Injeção Eletrônica automotiva voltado a resolver defeitos mecânicos e eletrônicos e veículos antigos e atuais, trabalho com equipamento de qualidade e já fiz vários cursos na área da mecânica.",
      title: "DÚ MECÂNICO",
      subtitle: "DIAGNÓSTICO AVANÇADO - INJEÇÃO ELETRÔNICA",
      contact: "Informações de Serviço e Agendamento pelo Whatsapp",
      phone: "wa::::99902-8626",
      delivery: false,
      email: "",
      address: "Rua Nicanor Nogueira, 13 - Vale do Sol",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/duMec.png"],
      order: { x: 0, y: 6 },
    },
    {
      _id: "620ace6313589700166baf5k",
      description: "MENSAL",
      title: "ESTACIONAMENTO TIRADENTES",
      subtitle: "HÁ VAGAS",
      contact: "",
      phone: "::::98898-6305/wa::::99920-3720",
      delivery: false,
      email: "",
      address:
        "Avenida Tiradentes, 280 - Centro - ao lado da Madeireira São Geraldo",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/estacionamentoTiradentes.png"],
      order: { x: 0, y: 7 },
    },
    {
      _id: "60f1d442828335001559a296",
      description:
        "3 anos de bons serviços | Atendimento de seg. à sab. das 7 ás 18h",
      title: "Borracharia Rua Nova do José Maria Borracheiro",
      subtitle: "MAIO MÊS DE ANIVERSÁRIO",
      contact: "PRECISA DE SOCORRO É SÓ LIGAR",
      phone: "::::99966-9884",
      email: "",
      address: "Rua Nova - próximo ao lavador do Luciano",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/borrachariaRuaNova.png"],
      order: { x: 6, y: 7 },
    },
    {
      _id: "620ace6313589700166baf4k",
      description: "Não cobramos frete",
      title: "Yamaha Motos",
      subtitle: "YAMAHA",
      contact: "Consultores de vendas",
      phone: "wa:Vânia:::99855-2703/wa:Tarcísio:::98832-2352",
      delivery: false,
      email: "",
      address: "Av. Israel Pinheiro - em frente Posto Padrão",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/yamahaMotos.png"],
      order: { x: 0, y: 8 },
    },
    {
      _id: "620ace6313589700166baf2e",
      description: "BATATAS | LANCHES | SALGADOS | SUCOS",
      title: "Batatop's",
      subtitle: "BURGUER",
      contact: "delivery - de 8 as 22 horas",
      phone: "wa::::99929-6089",
      delivery: false,
      email: "ig:@batatopss",
      address:
        "Rua Dr. João Couto, 718 - Centro - em frente a praça da feirinha",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/batatopsBurguer.png"],
      order: { x: 0, y: 9 },
    },
    {
      _id: "620ace6313589700166baf4a",
      description:
        "Cerveja gelada | Caldos | Porções diversas | Mascote, Pão com linguiça e o Extra Burguer",
      title: "Bar HORA EXTRA",
      subtitle: "PREPARANDO O MELHOR PARA VOCÊ.",
      contact: "",
      phone: ":Edinho:::99979-0437/::::99984-3818/:Patricia:::99966-0407",
      delivery: false,
      email: "",
      address: "Praça da Bandeira, 58 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/barHoraExtra.png"],
      order: { x: 0, y: 10 },
    },
    {
      _id: "620ace6313589700166baf4x",
      description:
        "Cerveja super gelada | Caldos variados | Porções deliciosas | Mascote | Estufa com salgados e tira gostos variados",
      title: "BAR E MERCEARIA DAS PRIMAS",
      subtitle:
        "Servimos almoço todos os domingos | DE TERÇA A DOMINGO A PARTIR DAS 12 HORAS",
      contact: "",
      phone: "wa::::99957-7827",
      delivery: false,
      email: "",
      address: "Praça da Bandeira, 8 - Matriz",
      neighborhood: "Matriz",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/barMerceariaDasPrimas.png"],
      order: { x: 0, y: 11 },
    },
    {
      _id: "620ace6313589700166baf5a",
      description: "",
      title: "IEIÉ",
      subtitle: "BEBIDAS",
      contact: "",
      phone: "::::98860-8826/wa::::99979-8085",
      delivery: true,
      email: "",
      address: "Avenida Tiradentes, 130 - loja-2",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/ieieBebidas.png"],
      order: { x: 6, y: 15 },
    },
    {
      _id: "620ace6313589700166baf5c",
      description:
        "VARIEDADES EM FERRAMENTAS, MÁQUINAS, TINTAS PARAFUSOS. TUBOS E CONEXÕES",
      title: "CASA RAMOS",
      subtitle: "Soluções para seu dia à dia",
      contact: "",
      phone: ":::32:3261-2546/wa::::98492-2747",
      delivery: false,
      email: "",
      address: "Rua Dr. João Couto, 15 - Loja 01 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/casaRamos.png"],
      order: { x: 0, y: 13 },
    },
    {
      _id: "621ace6313589700166baf5c",
      description: "A JK PODE TE AJUDAR NA GESTÃO DO FINANCEIRO DA SUA EMPRESA",
      title: "JK",
      subtitle: "BPO FINANCEIRO",
      contact: "",
      phone: "wa:::32:99979-60269",
      delivery: false,
      email: "ig:@jkbpofinanceiro/em:contato@jkbpofinanceiro.com.br",
      address: "",
      neighborhood: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681006",
      urls: ["/jkBPOF.png"],
      order: { x: 0, y: 14 },
    },
    {
      _id: "620ace6313589700166baf5e",
      description: "A MAIOR VARIEDADE - O MELHOR PREÇO",
      title: "DIDI",
      subtitle: "MATERIAIS DE CONSTRUÇÃO",
      contact: "Entrega em toda Região",
      phone: "::::3261-1020/::::3261-1456",
      delivery: false,
      email: "",
      address: "Rua Governador Valadares, 121",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/didMateriaisDeConstrucao.png"],
      order: { x: 6, y: 14 },
    },
    {
      _id: "622ace6313589700166baf4h",
      description:
        "CAR | CADASTRO DE ÁGUA | AEROLEVANTAMENTO | GEORREFERENCIAMENTO | LICENÇA DE MOTOSSERRA | USUCAPIÃO/ESTREMAÇÃO | LEVANTAMENTO TOPOGRÁFICO RURAL E URBANO | RETIFICAÇÃO/UNIFICAÇÃO/DESMEMBRAMENTO",
      title: "FocuX",
      subtitle: "Topografia e Georreferenciamento",
      contact: "",
      phone: ":::32:99962-6252/wa:::32:99176-5727",
      delivery: false,
      email: "em:projetos.focux@gmail.com",
      address: "",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/focux.png"],
      order: { x: 0, y: 16 },
    },
    {
      _id: "620ace6313589700166baf5i",
      description: "Especialista em Amigurumis e Tricotin",
      title: "Crochê da Dani",
      subtitle: "",
      contact: "Dani",
      phone: "wa::::99809-6092",
      delivery: false,
      email: "ig:@crochedadanioficial",
      address: "",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/crocheDaDani.png"],
      order: { x: 0, y: 18 },
    },
    {
      _id: "621ace6313589700166baf6i",
      description:
        'Corte | Hidratação | Luzes | Escova | Escova progressiva | Sobrancelhas | Sobrancelha micropigmentada - "Bendito seja o Senhor, rocha minha, que me adestra as mãos para a batalha..." (Salmo 144.1)',
      title: "Moisés",
      subtitle: "Cabeleireiro Unissex",
      contact: "25 anos de bons serviços - Sempre algo mais para realçar",
      phone: "wa::::99929-1099/::::3261-1099",
      delivery: false,
      email: "",
      address: "Rua Getúlio Vargas, 93-B - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/moises.png"],
      order: { x: 0, y: 19 },
    },
    {
      _id: "620ace6313589700166baf4i",
      description:
        "moda básica, abadás, linha hospitalar, camisas personalizadas, uniformes escolares, esportivos e profissionais",
      title: "D&M UNIFORMES",
      subtitle: "A VIDA TODA COM VOCÊ",
      contact: "",
      phone: "wa:::32:3261-2592",
      delivery: false,
      email: "ig:uniformesdem/fb:uniformesdem",
      address:
        "Rua Governador Valadares, 64 - Centro (em frente à Caixa Econômica)",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/dmUniformes.png"],
      order: { x: 0, y: 20 },
    },
    {
      _id: "620ace6313589700166baf4o",
      description:
        "DOMINGOS E FERIADOS ABERTO ATÉ ÀS 13H | ASSADOS EM GERAL, SUÍNOS, BOVINOS, AVES, CERVEJA E REFRIGERANTES GELADOS",
      title: "AÇOUGUE & BAR São Joaquim",
      subtitle: "O melhor tira gosto é você quem escolhe!",
      contact: "Aceltamos todos os cartões de crédito. Reizinho - Disk Entrega",
      phone: "::::99814-1401",
      delivery: true,
      email: "",
      address: "Rua Carlos Pellegrine Rocha, 314 - Bairro José Maria Fam",
      neighborhood: "José Maria Fam",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/saoJoaquimAcougueBar.png"],
      order: { x: 0, y: 22 },
    },
    {
      _id: "620ace6313589700166baf4p",
      description: "",
      title: "POPULAR GÁS E ÁGUA",
      subtitle: "",
      contact: "Samuel",
      phone: "wa:::32:99966-4955/wa:::32:99924-4955",
      delivery: false,
      email: "",
      address: '"Vem comigo"',
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/popularGasAgua.png"],
      order: { x: 0, y: 23 },
    },
    {
      _id: "620ace6313589700166baf4q",
      description: "",
      title: "Hortifruti e Mercado Central",
      subtitle: "ÁGUA E GÁS",
      contact: "Telefone e Whatsapp",
      phone: "wa:::32:98810-4021",
      delivery: false,
      email: "",
      address: 'Rua Doutor Fortes Bustamantes, 63 - "Rua do Taxi"',
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/hortifrutiCentral.png"],
      order: { x: 0, y: 24 },
    },
    {
      _id: "620ace6313589700166baf4r",
      description: "CARNE BOVINA, SUINA, AVES E LINGUIÇA",
      title: "Açougue Santa Rita",
      subtitle: "O melhor para você todos os dias",
      contact: "Direção: Geovani - Disk Entrega:",
      phone: "wa::::99801-6770/::::99836-4328",
      delivery: true,
      email: "",
      address: "Rua Coronel José Mendes, 355 - Próximo ao Bar do Fumaça",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/acougueSantaRita.png"],
      order: { x: 6, y: 24 },
    },
    {
      _id: "61bbd708823d5200164b17cc",
      description:
        "BOI, PORCO, PEIXE, FRANGO FRESCO | COMIDAS VARIADAS | A PARTIR DE 3ª FEIRA: ESPETINHOS NA BRASA / TODOS OS DIAS: frango resfriado, frango em pedaços, peixes, came fresca de boi e porco e frios em geral feijão cosido, lasanha, canelone, rondele e fricassê",
      title: "ARMAZÉM DO FRANGO / Forte Frios",
      subtitle:
        "Aos finais de semana trange assado pernil assado / AOS FINAIS DE SEMANA: CARNE E FRANGO ASSADO",
      contact: "",
      phone: "::::99970-8535/::::3261-7024",
      delivery: false,
      email: "",
      address:
        "Avenida Tiradentes, 200 - Centro / Rua Duque de Caxias, 119 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/armazemDoFrangoFortesFrios.png"],
      order: { x: 0, y: 25 },
    },
    {
      _id: "620ace6313589700166baf4c",
      description: "BOLOS - TORTAS - PAES - BISCOITOS",
      title: "Bragança",
      subtitle: "PADARIA E CONFEITARIA",
      contact: "Disk Entrega",
      phone: "::::3261-2750",
      delivery: true,
      email: "",
      address: "Rua Coronel José Dutra, 465",
      neighborhood: "",
      city: "SÃO JOÃO NEPOMUCENO - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/padariaBraganca.png"],
      order: { x: 0, y: 26 },
    },
    {
      _id: "620ace6313589700166baf4n",
      description:
        "[ALUGUEL] Kitnet: 1 quarto, cozinha, banheiro e área - Rua Paulo Rocha - R$350,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro - Avenida Israel Pinheiro - R$400,00 + taxas | Casa - 2 quartos, sala, cozinha, banheiro, área (cômodos pequenos) - Rua Joaquim Cruz - R$400,00 + taxas | Casa - 3 quartos, sala, cozinha, banheiro, área, garagem e terraço Rua Joaquim Cruz - R$ 750,00 | Casa - 3 quartos, sala, cozinha, banheiro, área grande, quintal grande e banheiro externo - Rua Cândido Noronha R$1200,00 | Casa - 3 quartos, sala, cozinha, banheiro, área, varanda - Rua Doutor João Couto R$1100,00 | Apto. 3 quartos, sala, cozinha, banheiro e área - Travessa João Goulart - R$700,00 + taxas | Apto - 4 quartos, sala, cozinha, banheiro e área - Rua Governador Valadares - R$1.200,00 | Loja - Rua Dr. João Sarmento - R$ 500,00 + taxas | Loja - Aliança Shopping - Pisos 1, 2 e 3 - Lojas de R$1077,00 até R$2.810,00 + taxas | Loja - Rua Cavalheiro Verardo - R$1500,00 | Loja - Avenida Carlos Alves - R$600,00 | Loja - Rua Coronel José Dutra (Antigo APOIO) - R$5.200,00 | Loja Rua Péricles Mendonça (em frente energisa) - R$1.400,00 | Galpão - Rua Luiz Brum Sales - R$600,00 | Galpão - Rua Carlos Pelegrini Rocha - R$750,00 | Galpão - Rua João 23 - R$500,00 | Loja - Rua dos Henriques - R$2400,00 - [VENDA] Lote Novo Horizonte - 1.000m² R$95.000,00 | Lote Novo Horizonte - 338m² R$75.000,00 | Lote Vivendas do Barão de 1000m², plano | Lote José M. Fam 504m², com estrutura pronta de 56m² para construir por cima | Lote Cond. Altos dos Pinheiros - lote 8, semi-plano com 201,7m² | Casa + Lote Santa Terezinha: área total de 600m² | Casa Centenário: 2 quartos, sala, banheiro, quintal com cozinha e quarto, piscina, garagem 3 carros, terraço coberto, telha galvanizada | Casa José Maria Fam: 3 quartos, sala, cozinha, banheiro, quintal, lavanderia e garagem | Casa Vivendas do Barão: 2 quartos, sala, cozinha, banheiro, garagem e área | Apto. São José: 1 a 3 quartos, sala, cozinha, banheiro, área | Apto. Centro 3 quartos (suite), sala, cozinha, banheiro, área, banheiro e garagem | Oportunidade para Empreendedores - Av. Israel Pinheiro - Em frente ao Clube Democráticos - 10.000m² com 180m de frente | Oportunidade para Empreendedores - Área Central com 6000m² com casa de 2 pavimentos | Casa Alto dos Pinheiros - Varandão, 3 quartos, sala, suite, lavabo, lavanderia, quintal grande, espaço gourmet com churrasqueira, piscina com banho, campo de futebol com 2 banheiros, garagem 3 carros com banheiro",
      title: "IMOBILIÁRIA CASA LEITE",
      subtitle:
        "ADMINISTRAÇÃO - VENDA - ADVOCACIA | Você empresta sua confiança. Nós lhe damos garantia.",
      contact: "CRECI/MG 9677 E 17.181 LTDA.",
      phone: "::::3261-1840/wa:::32:98828-4524",
      delivery: false,
      email: "ig:@imobiliariacasaleite",
      address: "Rua Coronel José Dutra, 487/101",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "", //Entre em contato pelo nosso whatsapp (32)  Acesse no instagram
      qrCode: "",
      adFormatId: "620ad11413589700166baf4c",
      urls: ["/casLeit.png"],
      order: { x: 0, y: 27 },
    },
    {
      _id: "620ace6313589700166baf5g",
      description: "",
      title: "TONHO SEGUROS",
      subtitle: "",
      contact: "",
      phone: ":Tonho::32:99963-5280/:Lilian::21:98035-8520/:fixo::32:3261-5232",
      delivery: false,
      email: "",
      address: "",
      neighborhood: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/tonhoSeguros.png"],
      order: { x: 0, y: 32 },
    },
    {
      _id: "620ace6323589700166baf5g",
      description:
        "Serviços | Lavagens em geral | Higienização | Polimento | Vitrificação",
      title: "KA",
      subtitle: "ESTÚDIO AUTOMOTIVO",
      contact: "Segunda a Sábado busco e entrego à domicilio",
      phone: "wa::::99987-2928",
      delivery: true,
      email: "ig:@ka_estudioautomotivo",
      address: "Rua Capitão Ferreira Campos, 105 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681006",
      urls: ["/kaEstAuto.png"],
      order: { x: 0, y: 32 },
    },
    {
      _id: "620ace6313589700166baf4d",
      description: "",
      title: "Mercado Cebolinha",
      subtitle: "",
      contact: "Entrega em domicilio grátis | Preços Baixos",
      phone: "::::3261-3258",
      delivery: true,
      email: "",
      address: "Rua Daniel Sarmento, 131",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/merCebo.png"],
      order: { x: 6, y: 32 },
    },
    {
      _id: "620ace6313589700266baf4d",
      description: "Legumes, verduras e frutas frescas todos os dias",
      title: "Casa das Frutas",
      subtitle: "",
      contact: "entregamos em sua casa",
      phone: "::::3261-6231",
      delivery: true,
      email: "",
      address: "Rua Duque de Caxias, 6 - loja 1 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/casaFrut.png"],
      order: { x: 6, y: 33 },
    },
    {
      _id: "623ace6313589700166baf4e",
      description:
        "Recupere sua autoestima - implante dentário | VOLTAR A SORRIR COM SEGURANÇA PODE SER RÁPIDO E INDOLOR",
      title: "ODONTO Company",
      subtitle: "A MAIOR DO MUNDO",
      contact: "agende já sua avaliação",
      phone: ":::32:3261-3322/:::32:99954-5466",
      delivery: false,
      email: "",
      address: "Rua Duque de Caxias, 70",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/odontoComp.png"],
      order: { x: 0, y: 35 },
    },
    {
      _id: "620ace6313589700166baf4u",
      description:
        "Artesanato mineiro em: cerâmica, madeira, tecido, tapeçaria, sabonetes artesanais e outros",
      title: "Mãos Arteiras",
      subtitle: "",
      contact: "",
      phone: "::::3261-2762",
      delivery: false,
      email: "",
      address: "Rua Doutor Fortes Bustamantes, 4 - loja 2",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/maosArteiras.png"],
      order: { x: 0, y: 36 },
    },
    {
      _id: "620ace6313589700166baf4v",
      description: "",
      title: "MAJ SILK",
      subtitle: "",
      contact: "Jean",
      phone: "wa::::99959-4442",
      delivery: false,
      email: "em:maisilk@gmail.com",
      address: "Rua Expedicionário Garcia Lopes, 374 - Centro",
      neighborhood: "Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/majSilkJean.png"],
      order: { x: 6, y: 39 },
    },
    {
      _id: "620ace6313589700166baf4t",
      description:
        "ACESSE O JORNAL ONLINE - futuramente com músicas, jogos e animações",
      title: "OPÇÃO",
      subtitle: "O SEU GUIA DE COMPRAS",
      contact: "",
      phone: "",
      delivery: false,
      email: "",
      address: "",
      neighborhood: "",
      city: "",
      link: "https://infop.czar.dev/",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/opcaoOnline.png"],
      order: { x: 0, y: 40 },
    },
    {
      _id: "620ace6313589700166baf6a",
      description:
        "Uma página ou site hoje é parte de abrir ou manter seu negócio | UM SERVIÇO OU APLICATIVO ONLINE ABREM NOVAS POSSIBILIDADES - ARTE E DESIGN | HOSTING | SERVIÇO DE NUVEM E ARMAZENAMENTO DE DADOS | MONITORAMENTO 24/7 | ACESSO A ESTATISTICAS | SUPORTE TÉCNICO | SEGURANÇA | CONTRA QUEDAS E HACKEAMENTO",
      title: "CZAR",
      subtitle: "Projetos em TI",
      contact: "",
      phone: "wa:Lucas Marcus::32:99926-3905",
      email: "em:contato@czar.dev",
      address: "",
      city: "São João del-Rei - MG",
      link: "https://czar.dev/",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/czar.png"],
      order: { x: 0, y: 41 },
    },
    {
      _id: "620ace6313589700366baf6a",
      description:
        "Venha se deliciar com porções variadas, aquela cerveja gelada e um Restaurante Sell service.",
      title: "PORÃO BAR",
      subtitle:
        "Bar e Restaurante - Funcionamos aos sábados, domingos e feriados",
      contact:
        "Aceitamos cartão de crédito e PIX - Seu local de descanso e lazer",
      phone: "::::99968-2511",
      email: "",
      address: "Estrada Roca Grande/Araci",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/poraoBar.png"],
      order: { x: 0, y: 42 },
    },
    {
      _id: "620ace6313589700466baf4y",
      description:
        "Requisitos: - Experiência na área. - Montagem e instalação de Letreiros e serviços de serralheria em geral. Salário + Benefícios",
      title: "Imagem Comunicação Visual",
      subtitle: "SERRALHEIRO COMUNICACAO VISUAL",
      contact: "Enviar currículo para",
      phone: "wa:::32:98854-7672",
      delivery: true,
      email: "",
      address: "Temos Vagas",
      neighborhood: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681006",
      urls: ["/imagemCom.png"],
      order: { x: 0, y: 43 },
    },
    {
      _id: "620ace6313589700166baf4y",
      description: "AGRADECEMOS A PREFERÊNCIA",
      title: "BARÃO LANCHES",
      subtitle: "Você merece a melhor!",
      contact: "Disk Entrega",
      phone: "wa::::99996-3853",
      delivery: true,
      email: "",
      address: "na Praça do Coronel",
      neighborhood: "Centro",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/baraoLanches.png"],
      order: { x: 6, y: 43 },
    },
    {
      _id: "620ace6313589700166baf5b",
      description: "das 3 horas da tarde às 11 horas da noite",
      title: "Nogueira Lanches",
      subtitle: "Agradecemos a preferência",
      contact: "Disk Entrega:",
      phone: ":::32:99957-4247/:::32:3261-4764",
      delivery: true,
      email: "",
      address: "",
      neighborhood: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/nogueiLanches.png"],
      order: { x: 6, y: 44 },
    },
    {
      _id: "620ace6323589700166baf5d",
      description:
        "PELÍCULA DE PROTEÇÃO | FECHAMENTO DE PIA | VIDROS EM GERAL | GUARDA-CORPO | ESPELHOS | JANELAS | PORTAS | BOX",
      title: "VB",
      subtitle: "VIDRAÇARIA VIDROS BEN",
      contact: "",
      phone: ":::32:98463-3307",
      delivery: false,
      email: "ig:@vidraçariavidrosben",
      address: "Rua José Felipe, 95 - Bairro Olaria",
      neighborhood: "Bairro Olaria",
      city: "Descoberto - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/vbVid.png"],
      order: { x: 0, y: 45 },
    },
    {
      _id: "620ace6333589700166baf5d",
      description:
        "SOLUÇÕES RESIDENCIAIS Chega de mofo e infiltração! Tinta borracha líquida Multiuso (5 anos de garantia) indicado para: Parede | Lage | Telhado | Portões | Madeira - Pedras Cristais, Pedras Naturais, Cimento Queimado e Grafiato.",
      title: "kasa",
      subtitle: "DE CORES",
      contact: "",
      phone: "wa:::32:99937-7141",
      delivery: false,
      email: "ig:@kasadecores",
      address: "Pátio da Fábrica, loja 05",
      neighborhood: "",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/kasaCores.png"],
      order: { x: 0, y: 45 },
    },
    {
      _id: "620ace6313589700166baf5d",
      description:
        "COLAS, DURATEX, COMPENSADOS, PORTAS, JANELAS, FORROS, GUARNIÇÕES, TELHAS COLONIAL E AMIANTO, VERNIZES, ETC.",
      title: "MADEIREIRA São Geraldo",
      subtitle: "MADEIRAS EM GERAL",
      contact: "",
      phone: "::::3261-1977/::::3261-1662",
      delivery: false,
      email: "",
      address: "Av. Tiradentes, 298 - Centro",
      neighborhood: "Centro",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/madereiraSaoGeraldo.png"],
      order: { x: 6, y: 26 },
    },
    {
      _id: "620ace6313589700466baf4i",
      description:
        "Reduza até 95% da sua conta de ENERGIA ELÉTRICA | COMECE A ECONOMIZAR JÁ. SIMULE SEU FINANCIAMENTO",
      title: "VÊNUS",
      subtitle: "ENERGIA SOLAR",
      contact: "",
      phone: "wa:::32:99852-3025/wa:::24:98821-9007",
      delivery: false,
      email: "ig:venusenergiasolar",
      address: "Escritório: Rua dos Henriques, 46 - Caxangá",
      neighborhood: "Caxangá",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/venusEnegSol.png"],
      order: { x: 0, y: 48 },
    },
    // {
    //   _id: "620ace6313589700166baf5a",
    //   description: "",
    //   title: "IEIÉ",
    //   subtitle: "BEBIDAS",
    //   contact: "",
    //   phone: "::::98860-8826/wa::::99979-8085",
    //   delivery: true,
    //   email: "",
    //   address: "Avenida Tiradentes, 130 - loja-2",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/ieieBebidas.png"],
    //   order: { x: 0, y: 1 },
    // },
    // {
    //   _id: "620ace6313589700166baf5b",
    //   description: "das 3 horas da tarde às 11 horas da noite",
    //   title: "Nogueira Lanches",
    //   subtitle: "Agradecemos a preferência",
    //   contact: "Disk Entrega:",
    //   phone: ":::32:99957-4247/:::32:3261-4764",
    //   delivery: true,
    //   email: "",
    //   address: "",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/nogueiLanches.png"],
    //   order: { x: 6, y: 1 },
    // },
    // {
    //   _id: "621ace6313589700166baf4h",
    //   description:
    //     "OFICINA ESPECIALIZADA - SERVIÇOS, PEÇAS E ACESSÓRIOS PARA SUA BIKE",
    //   title: "MANINHO BIKE",
    //   subtitle: "Oficina Shop",
    //   contact: "",
    //   phone: "wa:::32:98826-4371",
    //   delivery: false,
    //   email: "ig:@maninho.oficina.bike.shop",
    //   address: "Rua Nazareth, 142 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/maniBike.png"],
    //   order: { x: 0, y: 2 },
    // },
    // {
    //   _id: "620ace6313589700166baf4o",
    //   description:
    //     "DOMINGOS E FERIADOS ABERTO ATÉ ÀS 13H | ASSADOS EM GERAL, SUÍNOS, BOVINOS, AVES, CERVEJA E REFRIGERANTES GELADOS",
    //   title: "AÇOUGUE & BAR São Joaquim",
    //   subtitle: "O melhor tira gosto é você quem escolhe!",
    //   contact: "Aceltamos todos os cartões de crédito. Reizinho - Disk Entrega",
    //   phone: "::::99814-1401",
    //   delivery: true,
    //   email: "",
    //   address: "Rua Carlos Pellegrine Rocha, 314 - Bairro José Maria Fam",
    //   neighborhood: "José Maria Fam",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/saoJoaquimAcougueBar.png"],
    //   order: { x: 0, y: 4 },
    // },
    // {
    //   _id: "620ace6313589700166baf4p",
    //   description: "",
    //   title: "POPULAR GÁS E ÁGUA",
    //   subtitle: "",
    //   contact: "Samuel",
    //   phone: "wa:::32:99966-4955/wa:::32:99924-4955",
    //   delivery: false,
    //   email: "",
    //   address: '"Vem comigo"',
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/popularGasAgua.png"],
    //   order: { x: 0, y: 5 },
    // },
    // {
    //   _id: "620ace6313589700166baf4q",
    //   description: "",
    //   title: "Hortifruti e Mercado Central",
    //   subtitle: "ÁGUA E GÁS",
    //   contact: "Telefone e Whatsapp",
    //   phone: "wa:::32:98810-4021",
    //   delivery: false,
    //   email: "",
    //   address: 'Rua Doutor Fortes Bustamantes, 63 - "Rua do Taxi"',
    //   neighborhood: "",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/hortifrutiCentral.png"],
    //   order: { x: 0, y: 6 },
    // },
    // {
    //   _id: "620ace6313589700166baf4r",
    //   description: "CARNE BOVINA, SUINA, AVES E LINGUIÇA",
    //   title: "Açougue Santa Rita",
    //   subtitle: "O melhor para você todos os dias",
    //   contact: "Direção: Geovani - Disk Entrega:",
    //   phone: "wa::::99801-6770/::::99836-4328",
    //   delivery: true,
    //   email: "",
    //   address: "Rua Coronel José Mendes, 355 - Próximo ao Bar do Fumaça",
    //   neighborhood: "",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/acougueSantaRita.png"],
    //   order: { x: 6, y: 6 },
    // },
    // {
    //   _id: "61bbd708823d5200164b17cc",
    //   description:
    //     "BOI, PORCO, PEIXE, FRANGO FRESCO | COMIDAS VARIADAS | A PARTIR DE 3ª FEIRA: ESPETINHOS NA BRASA / TODOS OS DIAS: frango resfriado, frango em pedaços, peixes, came fresca de boi e porco e frios em geral feijão cosido, lasanha, canelone, rondele e fricassê",
    //   title: "ARMAZÉM DO FRANGO / Forte Frios",
    //   subtitle:
    //     "Aos finais de semana trange assado pernil assado / AOS FINAIS DE SEMANA: CARNE E FRANGO ASSADO",
    //   contact: "",
    //   phone: "::::99970-8535/::::3261-7024",
    //   delivery: false,
    //   email: "",
    //   address:
    //     "Avenida Tiradentes, 200 - Centro / Rua Duque de Caxias, 119 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/armazemDoFrangoFortesFrios.png"],
    //   order: { x: 0, y: 7 },
    // },
    // {
    //   _id: "61b92ca6ff15c00016366596",
    //   description: "",
    //   title: "CASA DE CARNES SANTA RITA",
    //   subtitle: "O MELHOR PARA VOCÊ",
    //   contact: "AOS DOMINGOS FRANGO E CARNE ASSADA",
    //   phone: ":::32:3261-1952/wa::::99918-5852",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Duque de Caxias, 49 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/casaDeCarnesSantaRita.png"],
    //   order: { x: 0, y: 8 },
    // },
    // {
    //   _id: "620ace6313589700166baf4c",
    //   description: "BOLOS - TORTAS - PAES - BISCOITOS",
    //   title: "Bragança",
    //   subtitle: "PADARIA E CONFEITARIA",
    //   contact: "Disk Entrega",
    //   phone: "::::3261-2750",
    //   delivery: true,
    //   email: "",
    //   address: "Rua Coronel José Dutra, 465",
    //   neighborhood: "",
    //   city: "SÃO JOÃO NEPOMUCENO - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/padariaBraganca.png"],
    //   order: { x: 6, y: 8 },
    // },
    // {
    //   _id: "61bbd708823d5200164b16cc",
    //   description: "Seus olhos em boas mãos! | AGENDE JÁ SUA AVALIAÇÃO!",
    //   title: "ÓTICA VISALI",
    //   subtitle: "Um novo conceito em Ótica!",
    //   contact: "Tem sempre uma Clínica perto de Você",
    //   phone: ":::32:3571-2965/wa:::32:99945-2965",
    //   delivery: false,
    //   email: "",
    //   address:
    //     "Rua Doutor Dutra, 36, Centro / Rua Governador Valadares 74 - loja 2, Centro ",
    //   neighborhood: "Centro",
    //   city: "RIO POMBA - MG / SÃO JOÃO NEPOMUCENO - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/otiVisu.png"],
    //   order: { x: 0, y: 9 },
    // },
    // {
    //   _id: "620ace6313589700166baf4f",
    //   description:
    //     "HARMONIZAÇÃO FACIAL | BOTOX | PREENCHIMENTO LABIAL | BIOESTIMULADORES | FIOS DE SUSTENTAÇÃO",
    //   title: "VANESSA BIAZUTTI",
    //   subtitle: "biomédica esteta",
    //   contact: "Vanessa Biazutti",
    //   phone: "::::99938-2448",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Domingos Henriques de Gusmão, 56 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/vanessaBiazutti.png"],
    //   order: { x: 0, y: 10 },
    // },
    // {
    //   _id: "623ace6313589700166baf4e",
    //   description:
    //     "IMPLANTE UM SORRISO | De quais tratamentos você está precisando?",
    //   title: "ODONTO Company",
    //   subtitle: "A MAIOR DO MUNDO",
    //   contact: "agende já sua avaliação",
    //   phone: ":::32:3261-3322/:::32:99954-5466",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Duque de Caxias, 70",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/odoCom.png"],
    //   order: { x: 0, y: 11 },
    // },
    // {
    //   _id: "63b92ca6ff15c00016366596",
    //   description: "Completa linha de perfumaria à vista",
    //   title: "DROGARIA REDE INOVA | DROGARIAS DA SERRA",
    //   subtitle: "O MELHOR PARA VOCÊ",
    //   contact: "Disk Entrega",
    //   phone: "::::3265-1200",
    //   delivery: true,
    //   email: "",
    //   address: "Rua do Rosário, 60",
    //   neighborhood: "",
    //   city: "Descoberto - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/inovaSerra.png"],
    //   order: { x: 6, y: 23 },
    // },
    // {
    //   _id: "620ace6313589700166baf2e",
    //   description: "BATATAS | LANCHES | SALGADOS | SUCOS",
    //   title: "Batatop's",
    //   subtitle: "BURGUER",
    //   contact: "delivery - de 8 as 22 horas",
    //   phone: "wa::::99929-6089",
    //   delivery: false,
    //   email: "ig:@batatopss",
    //   address:
    //     "Rua Dr. João Couto, 718 - Centro - em frente a praça da feirinha",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/batatopsBurguer.png"],
    //   order: { x: 0, y: 13 },
    // },
    // {
    //   _id: "620ace6313589700166baf4e",
    //   description:
    //     "ARTIGOS PARA FESTAS JUNINAS, CUMBUCA PRA CALDOS, COLHER, ENFEITES, BANDEIRINHAS, CHAPÉU DE CAIPIRA, TOALHAS DESCATÁVEIS E MUITOS DOCES",
    //   title: "COMEMORANDO FESTAS",
    //   subtitle: "",
    //   contact: "",
    //   phone: "::::3261-3299/wa::::99902-2477",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Presidente Getúlio Vargas, 100 - Loja 2 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/comFest.png"],
    //   order: { x: 0, y: 14 },
    // },
    // {
    //   _id: "620ace6313589700166baf4x",
    //   description:
    //     "Cerveja super gelada | Caldos variados | Porções deliciosas | Mascote | Estufa com salgados e tira gostos variados",
    //   title: "BAR E MERCEARIA DAS PRIMAS",
    //   subtitle:
    //     "Servimos almoço todos os domingos | DE TERÇA A DOMINGO A PARTIR DAS 12 HORAS",
    //   contact: "",
    //   phone: "wa::::99957-7827",
    //   delivery: false,
    //   email: "",
    //   address: "Praça da Bandeira, 8 - Matriz",
    //   neighborhood: "Matriz",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/barMerceariaDasPrimas.png"],
    //   order: { x: 0, y: 15 },
    // },
    // {
    //   _id: "620ace6313589700166baf4a",
    //   description:
    //     "Cerveja gelada | Caldos | Porções diversas | Mascote, Pão com linguiça e o Extra Burguer",
    //   title: "Bar HORA EXTRA",
    //   subtitle: "PREPARANDO O MELHOR PARA VOCÊ.",
    //   contact: "",
    //   phone: ":Edinho:::99979-0437/::::99984-3818/:Patricia:::99966-0407",
    //   delivery: false,
    //   email: "",
    //   address: "Praça da Bandeira, 58 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/barHoraExtra.png"],
    //   order: { x: 0, y: 16 },
    // },
    // {
    //   _id: "620ace6313589700166baf4y",
    //   description: "AGRADECEMOS A PREFERÊNCIA",
    //   title: "BARÃO LANCHES",
    //   subtitle: "Você merece a melhor!",
    //   contact: "Disk Entrega",
    //   phone: "wa::::99996-3853",
    //   delivery: true,
    //   email: "",
    //   address: "na Praça do Coronel",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/baraoLanches.png"],
    //   order: { x: 0, y: 17 },
    // },
    // {
    //   _id: "620ace6313589700166baf4z",
    //   description:
    //     "CEREAIS, BEBIDAS EM GERAL | FRANGO INTEIRO E PEDAÇO, GÁS O MELHOR PREÇO | ENTREGAMOS: GÁS E COMPRAS",
    //   title: "Chave de Ouro",
    //   subtitle: "Bar e Mercearia",
    //   contact: "Sebastião Rosa",
    //   phone: "::::99937-3616",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Capitão Ferreira Campos, 93 - saída para Descoberto",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/barMerceariaChaveDeOuro.png"],
    //   order: { x: 6, y: 17 },
    // },
    // {
    //   _id: "620ace6313589700166baf5i",
    //   description: "Especialista em Amigurumis e Tricotin",
    //   title: "Crochê da Dani",
    //   subtitle: "",
    //   contact: "Dani",
    //   phone: "wa::::99809-6092",
    //   delivery: false,
    //   email: "ig:@crochedadanioficial",
    //   address: "",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/crocheDaDani.png"],
    //   order: { x: 0, y: 18 },
    // },
    // {
    //   _id: "621ace6313589700166baf5i",
    //   description: "Presente no dia dos Namorados",
    //   title: "Zeca",
    //   subtitle: "A MANEIRA MAIS FÁCIL DE PRESENTEAR A QUEM VOCÊ AMA!",
    //   contact: "",
    //   phone: "::::3261-3959/::::3261-1191",
    //   delivery: false,
    //   email: "",
    //   address:
    //     "Rua Dr. Fortes Bustamantes, 74 / Rua Duque de Caxias, 135/4 - SPORTS",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/zeca.png"],
    //   order: { x: 0, y: 19 },
    // },
    // {
    //   _id: "622ace6313589700166baf4h",
    //   description:
    //     "CAR | CADASTRO DE ÁGUA | AEROLEVANTAMENTO | GEORREFERENCIAMENTO | LICENÇA DE MOTOSSERRA | USUCAPIÃO/ESTREMAÇÃO | LEVANTAMENTO TOPOGRÁFICO RURAL E URBANO | RETIFICAÇÃO/UNIFICAÇÃO/DESMEMBRAMENTO",
    //   title: "FocuX",
    //   subtitle: "Topografia e Georreferenciamento",
    //   contact: "",
    //   phone: ":::32:99962-6252/wa:::32:99176-5727",
    //   delivery: false,
    //   email: "em:projetos.focux@gmail.com",
    //   address: "",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/focux.png"],
    //   order: { x: 0, y: 20 },
    // },
    // {
    //   _id: "621ace6313589700166baf6i",
    //   description:
    //     "Corte | Hidratação | Luzes | Escova | Escova progressiva | Sobrancelhas | Sobrancelha micropigmentada",
    //   title: "Moisés",
    //   subtitle: "Cabeleireiro Unissex",
    //   contact: "25 anos de bons serviços - Sempre algo mais para realçar",
    //   phone: "wa::::99929-1099/::::3261-1099",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Getúlio Vargas, 93-B - Centro",
    //   neighborhood: "Centro",
    //   city: '"Bendito seja o Senhor, rocha minha, que me adestra as mãos para a batalha..." (Salmo 144.1)',
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/moises.png"],
    //   order: { x: 0, y: 22 },
    // },
    // {
    //   _id: "620ace6313589700166baf6f",
    //   description:
    //     "Cortes tradicionais | Cortes modernos exclusividade em cortes masculino e feminino - Especialista em cabelo masculino",
    //   title: "João Cabeleireiro",
    //   subtitle: "Unissex - 68 ANOS DE BONS SERVIÇOS",
    //   contact: "Atendimento de 7 às 19h",
    //   phone: ":::32:3261-5848",
    //   delivery: false,
    //   email: "",
    //   address: "Praça Dr. Carlos Alves, Loja 1 - Beco da União",
    //   neighborhood: "",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681006",
    //   urls: ["/joaoCab.png"],
    //   order: { x: 0, y: 23 },
    // },
    // {
    //   _id: "620ace6313589700166baf4i",
    //   description:
    //     "moda básica, abadás, linha hospitalar, camisas personalizadas, uniformes escolares, esportivos e profissionais",
    //   title: "D&M UNIFORMES",
    //   subtitle: "A VIDA TODA COM VOCÊ",
    //   contact: "",
    //   phone: "wa:::32:3261-2592",
    //   delivery: false,
    //   email: "ig:uniformesdem/fb:uniformesdem",
    //   address:
    //     "Rua Governador Valadares, 64 - Centro (em frente à Caixa Econômica)",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/dmUniformes.png"],
    //   order: { x: 0, y: 25 },
    // },
    // {
    //   _id: "620ace6313589700166baf4n",
    //   description:
    //     "[ALUGUEL] Kitnet: 1 quarto, cozinha, banheiro e área - Rua Paulo Rocha - R$400,00 + taxas | Kitnet: 1 quartos, sala, cozinha, banheiro e área-Rua João Sarmento - R$ 450,00 | Kitnet: 1 quarto-sala, cozinha e banheiro - R. Coronel José Dutra - R$ 500,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro - Avenida Israel Pinheiro - R$400,00 + taxas | Casa: 2 quartos, sala, cozinha, banheiro, área. (cômodos pequenos) - Rua Joaquim Cruz - R$400,00 + taxas | Casa: 3 quartos, sala, cozinha, banheiro, área, garagem e terraço - Rua Joaquim Cruz - R$ 750,00 | Apto: 3 quartos, sala, cozinha, banheiro e área - Travessa João Goulart - R$700,00 + taxas | Apto: 4 quartos, sala, cozinha, banheiro e área - Rua Gov. Valadares-R$ 1.200,00 | Loja: Rua Dr. João Sarmento - R$ 600,00 + taxas | Loja: Aliança Shopping - Pisos 1, 2 e 3 | Lojas: R$ 1077,00 até R$2.810,00 + taxas. | Loja: R. Cavalheiro Verardo - R$ 1500,00. | Loja: Avenida Carlos Alves - R$ 600,00 | Loja - Rua Coronel José Dutra (Antigo APOIO) - R$5.200,00 | Loja: Rua Péricles Mendonça (em frente energisa) - R$ 1.400,00 | Galpão: Rua Luiz Brum Sales - R$600,00 | Galpão: Rua Carlos Pelegrini Rocha - R$ 750,00 - [VENDA] Lote Novo Horizonte: 1.000 m² R$95.000,00 | Lote Novo Horizonte: 338m² R$75.000,00 | Lote Vivendas do Barão de 1000m³, plano. | Lote José M. Fam 504m², com estrutura pronta de 56m² para construir por cima. | Lote Cond. Altos dos Pinheiros - lote 8, semi- plano com 201,7m² | Casa + Lote Santa Terezinha: área total de 600m² | Casa Centenário: 2 quartos, sala, banheiro, quintal com cozinha e quarto, piscina, garagem 3 carros, terraço coberto, telha galvanizada | Casa José Maria Fam: 3 quartos, sala, cozinha, banheiro, quintal, lavanderia e garagem | Casa Vivendas do Barão: 2 quartos, sala, cozinha, banheiro, garagem e área. | Apto. São José: 1 a 3 quartos. sala, cozinha, banheiro, área. | Apto. Centro: 3 quartos (suite), sala, cozinha, banheiro, área, banheiro e garagem | Oportunidade para Empreendedores - Av. Israel Pinheiro Em frente ao Clube Democráticos 10.000m² com 180m de frente. | Oportunidade para Empreendedores - Área Central com 6000m² com casa de 2 pavimentos. | Casa Alto dos Pinheiros Varandão, 3 quartos, sala, suite, lavabo, lavanderia, quintal grande, espaço gourmet com churrasqueira, piscina com banho, campo de futebol com 2 banheiros, garagem 3 carros com banheiro.",
    //   title: "IMOBILIÁRIA CASA LEITE",
    //   subtitle:
    //     "ADMINISTRAÇÃO - VENDA - ADVOCACIA | Você empresta sua confiança. Nós lhe damos garantia.",
    //   contact: "CRECI/MG 9677 E 17.181 LTDA.",
    //   phone: "::::3261-1840/wa:::32:98828-4524",
    //   delivery: false,
    //   email: "ig:@imobiliariacasaleite",
    //   address: "Rua Coronel José Dutra, 487/101",
    //   neighborhood: "",
    //   city: "São João Nepomuceno - MG",
    //   link: "", //Entre em contato pelo nosso whatsapp (32)  Acesse no instagram
    //   qrCode: "",
    //   adFormatId: "620ad11413589700166baf4c",
    //   urls: ["/imbCasaLeite.png"],
    //   order: { x: 0, y: 27 },
    // },
    // {
    //   _id: "60f603e2557aac0015cca542",
    //   description:
    //     "com teste do sistema de injeção com Aparelho Raster - equipamento de análise e limpeza de injetores de combustivel | VENDAS DE BATERIAS, SILENCIOSO, TROCA DE ÓLEO E PEÇAS EM GERAL | Serviços em carros nacional e importado | atendimento 24 horas",
    //   title: "MECÂNICA E LOJA CARNEIRINHO",
    //   subtitle: "MECÂNICA EM GERAL",
    //   contact: "",
    //   phone: ":::32:3261-4079/::::99965-5864",
    //   delivery: false,
    //   email: "",
    //   address: "Av. Celso Cosme de Castro, 1385 - Chácara dos Palmares",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/mecanicaCarneirinho.png"],
    //   order: { x: 0, y: 32 },
    // },
    // {
    //   _id: "620ace6313589700166baf4k",
    //   description: "Não cobramos frete",
    //   title: "Yamaha Motos",
    //   subtitle: "YAMAHA",
    //   contact: "Consultores de vendas",
    //   phone: "wa:Vânia:::99855-2703/wa:Tarcísio:::98832-2352",
    //   delivery: false,
    //   email: "",
    //   address: "Av. Israel Pinheiro - em frente Posto Padrão",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/yamahaMotos.png"],
    //   order: { x: 0, y: 33 },
    // },
    // {
    //   _id: "620ace6313589700166baf5k",
    //   description: "MENSAL",
    //   title: "ESTACIONAMENTO TIRADENTES",
    //   subtitle: "HÁ VAGAS",
    //   contact: "",
    //   phone: "::::98898-6305/wa::::99920-3720",
    //   delivery: false,
    //   email: "",
    //   address:
    //     "Avenida Tiradentes, 280 - Centro - ao lado da Madeireira São Geraldo",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/estacionamentoTiradentes.png"],
    //   order: { x: 6, y: 24 },
    // },
    // {
    //   _id: "620ace6313589700166baf4l",
    //   description:
    //     "PNEUS, BATERIAS, TROCA DE ÓLEO E AUTO PEÇAS - BORRACHARIA COMPLETA | SUPER TROCA DE ÓLEO | LUBRIFICANTE CARRO E MOTO",
    //   title: "GOLDIN",
    //   subtitle: "Tudo para o seu carro e moto",
    //   contact: "Disk",
    //   phone: "::::99838-7473",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Cônego Reis, 256 - Centro",
    //   neighborhood: "Centro",
    //   city: "SÃO JOÃO NEPOMUCENO - MG - PRÓXIMO DE VOCÊ",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/goldinPneus.png"],
    //   order: { x: 0, y: 35 },
    // },
    // {
    //   _id: "620ace6313589700166baf4t",
    //   description:
    //     "ACESSE O JORNAL ONLINE - futuramente com músicas, jogos e animações",
    //   title: "OPÇÃO",
    //   subtitle: "O SEU GUIA DE COMPRAS",
    //   contact: "",
    //   phone: "",
    //   delivery: false,
    //   email: "",
    //   address: "",
    //   neighborhood: "",
    //   city: "",
    //   link: "https://infop.czar.dev/",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/opcaoOnline.png"],
    //   order: { x: 0, y: 37 },
    // },
    // {
    //   _id: "620ace6313589700166baf4u",
    //   description:
    //     "Artesanato mineiro em: cerâmica, madeira, tecido, tapeçaria, sabonetes artesanais e outros",
    //   title: "Mãos Arteiras",
    //   subtitle: "",
    //   contact: "",
    //   phone: "::::3261-2762",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Doutor Fortes Bustamantes, 4 - loja 2",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/maosArteiras.png"],
    //   order: { x: 0, y: 38 },
    // },
    // {
    //   _id: "620ace6313589700166baf4v",
    //   description: "",
    //   title: "MAJ SILK",
    //   subtitle: "",
    //   contact: "Jean",
    //   phone: "wa::::99959-4442",
    //   delivery: false,
    //   email: "em:maisilk@gmail.com",
    //   address: "Rua Expedicionário Garcia Lopes, 374 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/majSilkJean.png"],
    //   order: { x: 6, y: 38 },
    // },
    // {
    //   _id: "620ace6313589700166baf6a",
    //   description:
    //     "Esteja visível nas redes e conquiste novos clientes - obtenha um site ou página web, para publicidade online - ARTES DIGITAL, LAYOUT, DESIGN, UX/UI | Seja visto pelos clientes em São João e Região - impulsionamento nas redes - GOOGLE ANALYTICS E OUTROS MONITORAMENTOS | Gerencie melhor seus negócios - essencial para estoques - BOM PARA MERCEARIAS, MERCADOS, DELIVERIES, HOTEIS ENTRE OUTROS | Não perca tempo com conversas interminavéis no Whatsapp - reduza confusões, seja prático e tenha agilidade - FAÇA COM QUE SEU CLIENTE PARTICIPE DA ESCOLHA E VEJA SEU CARDÁPIO ONLINE",
    //   title: "CZAR DEVS",
    //   subtitle: "",
    //   contact: "",
    //   phone: "wa:Lucas Marcus::32:99926-3905",
    //   delivery: false,
    //   email: "em:contato@czar.dev",
    //   address: "",
    //   neighborhood: "",
    //   city: "São João del-Rei",
    //   link: "https://czar.dev/",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/czar.jpeg"],
    //   order: { x: 0, y: 39 },
    // },
    // {
    //   _id: "620ace6313589700166baf5h",
    //   description:
    //     "IMPRESSÕES DE PROJETOS A0 (120x90)cm - A1 (90x60)cm - A2 (60x42)cm - A3 (42x29,7)cm",
    //   title: "ENGPAR",
    //   subtitle: "Soluções em Engenharia",
    //   contact: "",
    //   phone: "wa:::32:99943-2018",
    //   delivery: false,
    //   email:
    //     "fb:pauloparreirasjesus/em:eng.paulo.parreiras@gmail.com/in:eng.pauloparreiras",
    //   address: "Rua Governador Valadares, 6 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/engparSolucoesEmEngenharia.png"],
    //   order: { x: 0, y: 40 },
    // },
    // {
    //   _id: "620ace6313589700166baf8a",
    //   description:
    //     "Dia dos namorados | Ótimos preços e muitas novidades trabalhamos com cartão de crédito e débito",
    //   title: "LOJA SENSAÇÃO",
    //   subtitle: "presentes e utilidades",
    //   contact: "",
    //   phone: "wa:José Antônio:::99928-1211/wa:Regina:::99968-5358",
    //   delivery: false,
    //   email: "",
    //   address: "ao lado do Banco do Brasil",
    //   neighborhood: "",
    //   city: "O presente para o dia dos namorados está na LOJA SENSAÇÃO",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/lojaSensa.png"],
    //   order: { x: 0, y: 39 },
    // },
    // {
    //   _id: "620ace6313589700166baf4h",
    //   description:
    //     "Servimos a melhor muqueca e traíra sem espinha da região, carnes nobres | Venha saborear a melhor linguiça de vários sabores | Cerveja gelada, comida de qualidade, comida de qualidade, atendimento diferenciado é no CIROLA & REY DE MINAS | Servimos almoço de quarta a domingo de 11 às 15 horas e a noite funcionaremos à partir das 18 horas",
    //   title: "Bar e Restaurante CIROLA & REY DE MINAS",
    //   subtitle: "AGUARDAMOS SUA VISITA",
    //   contact: "servimos o melhor pão com tilápia e o famoso pão com linguiça",
    //   phone: "wa::::99969-8673/wa::::99844-8216",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Carlos Pellegrini Rocha, 220 - Loja 7 (Posto Vitória)",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/barRestauranteCirolaReyDeMinas.png"],
    //   order: { x: 0, y: 42 },
    // },
    // {
    //   _id: "620ace6313589700166baf5c",
    //   description:
    //     "VARIEDADES EM FERRAMENTAS, MÁQUINAS, TINTAS PARAFUSOS. TUBOS E CONEXÕES",
    //   title: "CASA RAMOS",
    //   subtitle: "Soluções para seu dia à dia",
    //   contact: "",
    //   phone: ":::32:3261-2546/wa::::98492-2747",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Dr. João Couto, 15 - Loja 01 - Centro",
    //   neighborhood: "Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/casaRamos.png"],
    //   order: { x: 0, y: 44 },
    // },
    // {
    //   _id: "620ace6313589700166baf5d",
    //   description:
    //     "COLAS, DURATEX, COMPENSADOS, PORTAS, JANELAS, FORROS, GUARNIÇÕES, TELHAS COLONIAL E AMIANTO, VERNIZES, ETC.",
    //   title: "MADEIREIRA São Geraldo",
    //   subtitle: "MADEIRAS EM GERAL",
    //   contact: "",
    //   phone: "::::3261-1977/::::3261-1662",
    //   delivery: false,
    //   email: "",
    //   address: "Av. Tiradentes, 298 - Centro",
    //   neighborhood: "Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/madereiraSaoGeraldo.png"],
    //   order: { x: 0, y: 45 },
    // },
    // {
    //   _id: "620ace6313589700166baf5e",
    //   description: "A MAIOR VARIEDADE - O MELHOR PREÇO",
    //   title: "DIDI",
    //   subtitle: "MATERIAIS DE CONSTRUÇÃO",
    //   contact: "Entrega em toda Região",
    //   phone: "::::3261-1020/::::3261-1456",
    //   delivery: false,
    //   email: "",
    //   address: "Rua Governador Valadares, 121",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/didMateriaisDeConstrucao.png"],
    //   order: { x: 0, y: 46 },
    // },
    // {
    //   _id: "620ace6313589700166baf5f",
    //   description:
    //     "fogões a gás, refrigeradores, microondas, ventiladores, lavadoras, liquidificadores, secador de cabelo, chuveiro elétrico, panela elétrica, chapinha de cabelo, ferro de passar roupas | SERVIÇO COM GARANTIA! ORÇAMENTO GRÁTIS! PREÇO IMBATÍVEL!",
    //   title: "LAZÁRO CONSERTA",
    //   subtitle: "conserto de Eletrodomésticos",
    //   contact: "Ligue Já!",
    //   phone: ":::32:99932-2694/wa:::32:99946-7834",
    //   delivery: false,
    //   email: "",
    //   address: "",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681006",
    //   urls: ["/lazaroConserta.png"],
    //   order: { x: 6, y: 45 },
    // },
    // {
    //   _id: "620ace6313589700166baf5g",
    //   description: "",
    //   title: "TONHO SEGUROS",
    //   subtitle: "",
    //   contact: "",
    //   phone: ":Tonho::32:99963-5280/:Lilian::21:98035-8520/:fixo::32:3261-5232",
    //   delivery: false,
    //   email: "",
    //   address: "",
    //   neighborhood: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/tonhoSeguros.png"],
    //   order: { x: 0, y: 47 },
    // },
    // {
    //   _id: "60f1d442828335001559a296",
    //   description:
    //     "3 anos de bons serviços | Atendimento de seg. à sab. das 7 ás 18h",
    //   title: "Borracharia Rua Nova do José Maria Borracheiro",
    //   subtitle: "MAIO MÊS DE ANIVERSÁRIO",
    //   contact: "PRECISA DE SOCORRO É SÓ LIGAR",
    //   phone: "::::99966-9884",
    //   email: "",
    //   address: "Rua Nova - próximo ao lavador do Luciano",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/borrachariaRuaNova.png"],
    //   order: { x: 0, y: 0 },
    // },
    // {
    //   _id: "60f1d44c828335001559a297",
    //   description:
    //     "Toda linha de móveis, sofás, colchões, eletrodomésticos | Especialista em aprovação de crédito | Carnê até 24x com entrada para 60 dias | Entregamos em toda região",
    //   title: "Competição Móveis",
    //   subtitle: "Ta pensando em comprar seus móveis?",
    //   contact:
    //     "Fale com o Lima, atendimento personalizado e sem a necessidade de você sair de casa.",
    //   phone: "wa:::32:99954-0240",
    //   email: "",
    //   address: "Rua Coronel José Dutra, 431 - ao lado do correio",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/competicaoMoveis.png"],
    //   order: { x: 0, y: 1 },
    // },
    // {
    //   _id: "60f603e2557aac0015cca542",
    //   description:
    //     "com teste do sistema de injeção com Aparelho Raster - equipamento de análise e limpeza de injetores de combustivel | VENDAS DE BATERIAS, SILENCIOSO, TROCA DE ÓLEO E PEÇAS EM GERAL | Serviços em carros nacional e importado | atendimento 24 horas",
    //   title: "MECÂNICA E LOJA CARNEIRINHO",
    //   subtitle: "MECÂNICA EM GERAL",
    //   contact: "",
    //   phone: ":::32:3261-4079/::::99965-5864",
    //   email: "",
    //   address: "Av. Celso Cosme de Castro, 1385 - Chácara dos Palmares",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/mCarneirinho.png"],
    //   order: { x: 0, y: 2 },
    // },
    // {
    //   _id: "60f61fe848a9e20015ae871a",
    //   description:
    //     "Quer anunciar seu imóvel ou comprar um, me procura que eu te ajudo",
    //   title: "Vinícius Tim",
    //   subtitle: "PENSOU EM IMÓVEIS?",
    //   contact: "CRECI 40300",
    //   phone: "wa:::32:99910-8956",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/viniciusTim.png"],
    //   order: { x: 0, y: 3 },
    // },
    // {
    //   _id: "60f74d8b9f3e6a0015b46a5d",
    //   description:
    //     "Carvão 3 kilos 11,75 pacote | Guarana Ita 2 litros 5,99 | Biscoito a partir de 1,49 | Atum ralado Gomes da Costa 6,99 | VÁRIAS PROMOÇÕES. VENHAM CONFERIR. ESPERAM POR VOCÊS! VERÁ SERIE DE UMA CARA DE BOMEKINO",
    //   title: "Mercearia JM",
    //   subtitle: "PROMOÇÃO PARA O DIA DAS MÃES",
    //   contact: "Joño e a Marlene",
    //   phone: "wa::::99960-1502",
    //   email: "",
    //   address: "Rua Prefeito Nagib Camilo Ayupi, 448 - Bairro Caxangá",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/merceariaJM.png"],
    //   order: { x: 0, y: 4 },
    // },
    // {
    //   _id: "61a0273dcd24bb001686e4cd",
    //   description:
    //     "PÃO INTEGRAL, PÃO DE CENOURA, PÃO DE CEBOLA, PÃO DE BETERRABA, PÃO DE BATATA, PÃO CEARENSE E BOLO BREVIDADE",
    //   title: "PADARIA Jujuba",
    //   subtitle: "",
    //   contact: "",
    //   phone: "::::99906-5630",
    //   email: "",
    //   address: "Rua Miguel Manso, 49 - Jujuba",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/padariaJujuba.png"],
    //   order: { x: 0, y: 5 },
    // },
    // {
    //   _id: "61b92ca6ff15c00016366596",
    //   description: "",
    //   title: "CASA DE CARNES SANTA RITA",
    //   subtitle: "O MELHOR PARA VOCÊ",
    //   contact: "AOS DOMINGOS FRANGO E CARNE ASSADA",
    //   phone: ":::32:3261-1952/wa::::99918-5852",
    //   email: "",
    //   address: "Rua Duque de Caxias, 49 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/casaCarnesSantaRita.png"],
    //   order: { x: 6, y: 5 },
    // },
    // {
    //   _id: "61bbd708823d5200164b17cc",
    //   description:
    //     "BOI, PORCO, PEIXE, FRANGO FRESCO | COMIDAS VARIADAS | A PARTIR DE 3ª FEIRA: ESPETINHOS NA BRASA / TODOS OS DIAS: frango resfriado, frango em pedaços, peixes, came fresca de boi e porco e frios em geral feijão cosido, lasanha, canelone, rondele e fricassê",
    //   title: "ARMAZÉM DO FRANGO / Forte Frios",
    //   subtitle:
    //     "Aos finais de semana trange assado pernil assado / AOS FINAIS DE SEMANA: CARNE E FRANGO ASSADO",
    //   contact: "",
    //   phone: "::::99970-8535/::::3261-7024",
    //   email: "",
    //   address:
    //     "Avenida Tiradentes, 200 - Centro / Rua Duque de Caxias, 119 - Centro",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/armFrangoForteFrios.png"],
    //   order: { x: 0, y: 6 },
    // },
    // {
    //   _id: "620ace6313589700166baf4b",
    //   description:
    //     "Galão de água 20 litros - Botijão de gás - Fardo de água com gás - Fardo de água sem gás",
    //   title: "NELSON GÁS E ÁGUA",
    //   subtitle: "Aceitamos: PIX, cartão de crédito e débito.",
    //   contact: "Disk Entrega",
    //   phone: "wa::::99941-3664",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/nelsonGasAgua.png"],
    //   order: { x: 0, y: 7 },
    // },
    // {
    //   _id: "620ace6313589700166baf4c",
    //   description: "BOLOS - TORTAS - PAES - BISCOITOS",
    //   title: "Bragança",
    //   subtitle: "PADARIA E CONFEITARIA",
    //   contact: "Disk Entrega",
    //   phone: "::::3261-2750",
    //   email: "",
    //   address: "Rua Coronel José Dutra, 465",
    //   city: "SÃO JOÃO NEPOMUCENO - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/padariaBraganca.png"],
    //   order: { x: 6, y: 7 },
    // },
    // {
    //   _id: "620ace6313589700166baf4d",
    //   description: "",
    //   title: "Mercado Cebolinha",
    //   subtitle: "",
    //   contact: "Entrega em domicilio grátis | Preços Baixos",
    //   phone: "::::3261-3258",
    //   email: "",
    //   address: "Rua Daniel Sarmento, 131",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/mercCebolinha.png"],
    //   order: { x: 0, y: 8 },
    // },
    // {
    //   _id: "620ace6313589700166baf3d",
    //   description: "",
    //   title: "Carlos Chagas",
    //   subtitle: "Laboratorio de Análises Clínicas",
    //   contact: "José Raimundo S. Gomes - Bioquimico Responsável CRF 7941",
    //   phone: ":::32:3261-2165",
    //   email: "",
    //   address: "Rua Getúlio Vargas, 12 - Centro",
    //   city: "SÃO JOÃO NEPOMUCENO - MINAS GERAIS",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/carlosChagas.png"],
    //   order: { x: 6, y: 8 },
    // },
    // {
    //   _id: "620ace6313589700166baf4e",
    //   description: "É FÁCIL TER O SORRISO QUE VOCÊ DESEJA!",
    //   title: "ODONTO Company",
    //   subtitle: "A MAIOR DO MUNDO E PARA VOCÊ TAMBÉM",
    //   contact: "agende já sua avaliação! tem sempre uma clinica perto de você",
    //   phone: ":::32:3261-3322/:::32:99954-5466",
    //   email: "",
    //   address: "Rua Duque de Caxias, 70",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/odontoCompany.png"],
    //   order: { x: 0, y: 9 },
    // },
    // {
    //   _id: "620ace6313589700166baf4f",
    //   description:
    //     "HARMONIZAÇÃO FACIAL | BOTOX | PREENCHIMENTO LABIAL | BIOESTIMULADORES | FIOS DE SUSTENTAÇÃO",
    //   title: "VANESSA BIAZUTTI",
    //   subtitle: "biomédica esteta",
    //   contact: "Vanessa Biazutti",
    //   phone: "::::99938-2448",
    //   email: "",
    //   address: "Rua Domingos Henriques de Gusmão, 56 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/vanessaBiazutti.png"],
    //   order: { x: 0, y: 10 },
    // },
    // {
    //   _id: "620ace6313589700166baf4g",
    //   description:
    //     "Funcionando todos os dias, servindo almoço e janta de Segunda a Quinta - Bom Apetite",
    //   title: "RESTAURANTE JANTINHA'S DELÍCIA",
    //   subtitle: "DESDE 2020",
    //   contact: "aceitamos cartões de crédito - disk entrega",
    //   phone: "wa::::99915-0483",
    //   email: "",
    //   address:
    //     "Rua Dr. João Cavalheiro - próximo ao aeroporto - Santa Terezinha",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/jantinhasDelicia.png"],
    //   order: { x: 0, y: 11 },
    // },
    // {
    //   _id: "620ace6313589700166baf4h",
    //   description:
    //     "Servimos a melhor muqueca e traíra sem espinha da região, carnes nobres | Venha saborear a melhor linguiça de vários sabores | Cerveja gelada, comida de qualidade, comida de qualidade, atendimento diferenciado é no CIROLA & REY DE MINAS | Servimos almoço de quarta a domingo de 11 às 15 horas e a noite funcionaremos à partir das 18 horas",
    //   title: "Bar e Restaurante CIROLA & REY DE MINAS",
    //   subtitle: "AGUARDAMOS SUA VISITA",
    //   contact: "servimos o melhor pão com tilápia e o famoso pão com linguiça",
    //   phone: "wa::::99969-8673/wa::::99844-8216",
    //   email: "",
    //   address: "Rua Carlos Pellegrini Rocha, 220 - Loja 7 (Posto Vitória)",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/basRestauranteCirolaReyDeMinas.png"],
    //   order: { x: 0, y: 12 },
    // },
    // {
    //   _id: "620ace6313589700166baf4i",
    //   description:
    //     "moda básica, abadás, linha hospitalar, camisas personalizadas, uniformes escolares, esportivos e profissionais",
    //   title: "D&M UNIFORMES",
    //   subtitle: "A VIDA TODA COM VOCÊ",
    //   contact: "",
    //   phone: "wa:::32:3261-2592",
    //   email: "ig:uniformesdem/fb:uniformesdem",
    //   address:
    //     "Rua Governador Valadares, 64 - Centro (em frente à Caixa Econômica)",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/D&MUniformes.png"],
    //   order: { x: 0, y: 14 },
    // },
    // {
    //   _id: "620ace6313589700166baf4j",
    //   description:
    //     "Reparo especializado em placa de iPhone e Android | Recuperação de aparelhos molhados (desoxidação) | Troca telas touch's | Troca de vidro | Troca de conectores de carga | Formatação/backupse em computadores e notebooks",
    //   title: "S.O.S CELULARES",
    //   subtitle: "ASSISTÊNCIA TÉCNICA ESPECIALIZADA",
    //   contact: "",
    //   phone: "wa::::99834-9375",
    //   email: "ig:garcia_nicolas02",
    //   address: "Rua Doutor João Couto, 701 - loja 1 - Centro",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/SOScelulares.png"],
    //   order: { x: 0, y: 16 },
    // },
    // {
    //   _id: "620ace6313589700166baf4k",
    //   description: "Não cobramos frete",
    //   title: "Yamaha Motos",
    //   subtitle: "YAMAHA",
    //   contact: "Consultores de vendas",
    //   phone: "wa:Vânia:::99855-2703/wa:Tarcísio:::98832-2352",
    //   email: "",
    //   address: "Av. Israel Pinheiro - em frente Posto Padrão",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/yamaha.png"],
    //   order: { x: 0, y: 17 },
    // },
    // {
    //   _id: "620ace6313589700166baf4l",
    //   description:
    //     "PNEUS, BATERIAS, TROCA DE ÓLEO E AUTO PEÇAS - BORRACHARIA COMPLETA | SUPER TROCA DE ÓLEO | LUBRIFICANTE CARRO E MOTO",
    //   title: "GOLDIN",
    //   subtitle: "Tudo para o seu carro e moto",
    //   contact: "Disk",
    //   phone: "::::99838-7473",
    //   email: "",
    //   address: "Rua Cônego Reis, 256 - Centro",
    //   city: "SÃO JOÃO NEPOMUCENO - MG - PRÓXIMO DE VOCÊ",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/goldin.png"],
    //   order: { x: 0, y: 18 },
    // },
    // {
    //   _id: "620ace6313589700166baf4m",
    //   description:
    //     "Chega de mofo e infiltração! TINTAS IMPERMEABILIZADAS PARA SUA CASA TRABALHAMOS COM: Pedras Travertino - Pedras Ferro - Pedra moledo - Pedra Espanha | TEXTURAS: Pedras Cristais - Pedras Naturais - Cimento Queimado Tradicional e Perolizado. HORÁRIO DE FUNCIONAMENTO: SEGUNDA A SEXTA: 8:00 ÁS 18:00H SÁBADO: 8:00 ÁS 12:00H",
    //   title: "KASA DE CORES",
    //   subtitle: "SOLUÇÕES RESIDENCIAIS",
    //   contact: "",
    //   phone: "wa:::32:99937-7141",
    //   email: "ig:@kasadecores",
    //   address: "Pátio da Fábrica, loja 05",
    //   city: "SÃO JOÃO NEPOMUCENO",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "620ad11413589700166baf4c",
    //   urls: ["/kasaDeCores.png"],
    //   order: { x: 0, y: 20 },
    // },
    // {
    //   _id: "620ace6313589700166baf4n",
    //   description:
    //     "[ALUGUEL] Kitnet: 1 quarto, cozinha, banheiro e área - Rua Carlos Stibler - R$400,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro e área - Rua Paulo Rocha R$400,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro - Avenida Israel Pinheiro - R$400,00 + taxas | Apto: 2 quarto, sala, cozinha, banheiro, garagem e terraço - Rua Elton Ferreira Amorin - R$780,00 + taxas | Casa - 2 quartos, sala, cozinha, banheiro, área. (cômodos pequenos) - Rua Joaquim Cruz - R$400,00 + taxas | Casa - 2 quartos, sala, cozinha, banheiro, área equintal - Rua Carlos Stiebler - R$ 500,00 | Casa - 3 quartos, sala, cozinha, banheiro, área, garagem e terraço - Rua Joaquim Cruz - R$ 750,00 | Casa - 3 quartos, sala, cozinha, banheiro, área egaragem - Rua Coronel Ricardo Martins - R$650,00 | Casa - 3 quartos, sala, cozinha, banheiro, área, garagem e terraço - Rua Alcebiades Valente - R$750,00 | Apto 3 quartos, sala, cozinha, banheiro e área - Travessa João Goulart - R$700,00 + taxas | Loja c/ sobre loja - Rua Barão do Rio Branco - R$2500,00 + Taxas | Loja - Rua Dr. João Sarmento R$600,00 + taxas | Loja - Aliança Shopping - Pisos 1,2 e 3-Lojas de R$1077,00 ate R$2.810,00 + taxas | Loja - Rua Cavalheiro Verardo - R$ 1500,00 | Loja - Rua Coronel José Dutra (Antigo APOIO) - R$5.200,00 | Loja - Rua Péricles Mendonça (em frenteenergisa) - R$1.400,00 | Galpão - Rua Luiz Brum Sales - R$600,00 [VENDA] Lote Novo Horizonte - 1.000m² R$95.000,00 | Lote Novo Horizonte - 338m² R$75.000,00 | Lote Vivendas do Barão de 1000m², plano | Lote José M. Fam - 504m², com estruturapronta de 56m² para construir por cima | Lote Cond. Altos dos Pinheiros - lote 8, semi-plano com 201,7m² | Casa + Lote Santa Terezinha: área total de 600m² | Casa Centenário: 2 quartos, sala, banheiro, quintal com cozinha e quarto, piscina, garagem 3 carros, terraço coberto, telha galvanizada | Casa José Maria Fam: 3 quartos, sala, cozinha, banheiro, quintal, lavanderia e garagem | Casa Vivendas do Barão: 2 quartos, sala,cozinha, banheiro, garagem e área | Apto. São José: 1 a 3 quartos, sala, cozinha, banheiro, área | Apto. Centro - 3 quartos (suíte), sala, cozinha, banheiro, área, banheiro e garagem | Oportunidade para Empreendedores - Av. Israel Pinheiro em frente ao Clube Democráticos - 10.000m² com 180m de frente | Oportunidade para Empreendedores - Área Central com 6000m² com casa de 2 pavimentos | Casa Alto dos Pinheiros - Varandão, 3 quartos, sala, suite, lavabo, lavanderia, quintal grande, espaço gourmet com churrasqueira, piscina com banho, campo de futebol com 2 banhos, garagem 3 carros com banheiro.",
    //   title: "IMOBILIÁRIA CASA LEITE",
    //   subtitle:
    //     "ADMINISTRAÇÃO - VENDA - ADVOCACIA | Você empresta sua confiança. Nós lhe damos garantia.",
    //   contact: "CRECI/MG 9677 E 17.181 LTDA.",
    //   phone: "::::3261-1840/wa:::32:98828-4524",
    //   email: "ig:@imobiliariacasaleite",
    //   address: "Rua Coronel José Dutra, 487/101",
    //   city: "São João Nepomuceno - MG",
    //   link: "", //Entre em contato pelo nosso whatsapp (32)  Acesse no instagram
    //   qrCode: "",
    //   adFormatId: "620ad11413589700166baf4c",
    //   urls: ["/imbCasaLeite.png"],
    //   order: { x: 0, y: 26 },
    // },
    // {
    //   _id: "620ace6313589700166baf4o",
    //   description:
    //     "DOMINGOS E FERIADOS ABERTO ATÉ ÀS 13H | ASSADOS EM GERAL, SUÍNOS, BOVINOS, AVES, CERVEJA E REFRIGERANTES GELADOS",
    //   title: "AÇOUGUE & BAR São Joaquim",
    //   subtitle: "O melhor tira gosto é você quem escolhe!",
    //   contact: "Aceltamos todos os cartões de crédito. Reizinho - Disk Entrega",
    //   phone: "::::99814-1401",
    //   email: "",
    //   address: "Rua Carlos Pellegrine Rocha, 314 - Bairro Jose Maria Fam",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/aBSaoJoaquim.png"],
    //   order: { x: 0, y: 32 },
    // },
    // {
    //   _id: "620ace6313589700166baf4p",
    //   description: "",
    //   title: "POPULAR GÁS E ÁGUA",
    //   subtitle: "",
    //   contact: "Samuel",
    //   phone: "wa:::32:99966-4955/wa:::32:99924-4955",
    //   email: "",
    //   address: '"Vem comigo"',
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/popularGasAgua.png"],
    //   order: { x: 0, y: 33 },
    // },
    // {
    //   _id: "620ace6313589700166baf4q",
    //   description: "",
    //   title: "Hortifruti e Mercado Central",
    //   subtitle: "ÁGUA E GÁS",
    //   contact: "Telefone e Whatsapp",
    //   phone: "wa:::32:98810-4021",
    //   email: "",
    //   address: 'Rua Doutor Fortes Bustamantes, 63 - "Rua do Taxi"',
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/hortifrutiCentral.png"],
    //   order: { x: 0, y: 34 },
    // },
    // {
    //   _id: "620ace6313589700166baf4r",
    //   description: "CARNE BOVINA, SUINA, AVES E LINGUIÇA",
    //   title: "Açougue Santa Rita",
    //   subtitle: "O melhor para você todos os dias",
    //   contact: "Direção: Geovani - Disk Entrega:",
    //   phone: "wa::::99801-6770/::::99836-4328",
    //   email: "",
    //   address: "Rua Coronel José Mendes, 355 - Próximo ao Bar do Fumaça",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/acougueSantaRita.png"],
    //   order: { x: 6, y: 34 },
    // },
    // {
    //   _id: "620ace6313589700166baf4s",
    //   description:
    //     "ENTREGAMOS GÁS, ÁGUA, CERVEJA, BEBIDAS EM GERAL, CHURRASQUEIRA, PICANHA, GELO, CORAÇÃO, BACON, BATATA CONGELADA, PEIXES E CARVÃO | Aceitamos cartões",
    //   title: "Marquinho GÁS",
    //   subtitle: "",
    //   contact: "Disk Entrega | Entrega Rápida",
    //   phone: "::fixo::3261-1470/wa::vivo::99952-3619",
    //   email: "",
    //   address: "Rua Capitão Brás, s/n - Centro",
    //   city: "SÃO JOÃO NEPOMUCENO - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/marquinhoGas.png"],
    //   order: { x: 0, y: 35 },
    // },
    // {
    //   _id: "620ace6313589700166baf4t",
    //   description:
    //     "ACESSE O JORNAL ONLINE - futuramente com músicas, jogos e animações",
    //   title: "OPÇÃO",
    //   subtitle: "O SEU GUIA DE COMPRAS",
    //   contact: "",
    //   phone: "",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "https://infop.czar.dev/",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/opcao.png"],
    //   order: { x: 0, y: 37 },
    // },
    // {
    //   _id: "620ace6313589700166baf4u",
    //   description:
    //     "Artesanato mineiro em: cerâmica, madeira, tecido, tapeçaria, sabonetes artesanais e outros",
    //   title: "Mãos Arteiras",
    //   subtitle: "",
    //   contact: "",
    //   phone: "::::3261-2762",
    //   email: "",
    //   address: "Rua Doutor Fortes Bustamantes, 4 - loja 2",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/maosArteiras.png"],
    //   order: { x: 0, y: 38 },
    // },
    // {
    //   _id: "620ace6313589700166baf4v",
    //   description: "",
    //   title: "MAJ SILK",
    //   subtitle: "",
    //   contact: "Jean",
    //   phone: "wa::::99959-4442",
    //   email: "em:maisilk@gmail.com",
    //   address: "Rua Expedicionário Garcia Lopes, 374 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/majSilk.png"],
    //   order: { x: 6, y: 38 },
    // },
    // {
    //   _id: "620ace6313589700166baf4x",
    //   description:
    //     "Cerveja super gelada | Caldos variados | Porções deliciosas | Mascote | Estufa com salgados e tira gostos variados",
    //   title: "BAR E MERCEARIA DAS PRIMAS",
    //   subtitle:
    //     "Servimos almoço todos os domingos | DE TERÇA A DOMINGO A PARTIR DAS 12 HORAS",
    //   contact: "",
    //   phone: "wa::::99957-7827",
    //   email: "",
    //   address: "Praça da Bandeira, 8 - Matriz",
    //   city: "São João Nepomuceno",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/barMercPrimas.png"],
    //   order: { x: 0, y: 41 },
    // },
    // {
    //   _id: "620ace6313589700166baf4y",
    //   description: "AGRADECEMOS A PREFERÊNCIA",
    //   title: "BARÃO LANCHES",
    //   subtitle: "Você merece a melhor!",
    //   contact: "Disk Entrega",
    //   phone: "wa::::99996-3853",
    //   email: "",
    //   address: "na Praça do Coronel",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/baraoLanches.png"],
    //   order: { x: 0, y: 39 },
    // },
    // {
    //   _id: "620ace6313589700166baf4z",
    //   description:
    //     "CEREAIS, BEBIDAS EM GERAL | FRANGO INTEIRO E PEDAÇO, GÁS O MELHOR PREÇO | ENTREGAMOS: GÁS E COMPRAS",
    //   title: "Chave de Ouro",
    //   subtitle: "Bar e Mercearia",
    //   contact: "Sebastião Rosa",
    //   phone: "::::99937-3616",
    //   email: "",
    //   address: "Rua Capitão Ferreira Campos, 93 - saída para Descoberto",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/barMercChaveDeOuro.png"],
    //   order: { x: 0, y: 40 },
    // },
    // {
    //   _id: "620ace6313589700166baf4a",
    //   description:
    //     "Cerveja gelada | Caldos | Porções diversas | Mascote, Pão com linguiça e o Extra Burguer",
    //   title: "Bar HORA EXTRA",
    //   subtitle: "PREPARANDO O MELHOR PARA VOCÊ.",
    //   contact: "",
    //   phone: ":Edinho:::99979-0437/::::99984-3818/:Patricia:::99966-0407",
    //   email: "",
    //   address: "Praça da Bandeira, 58 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/barHoraExtra.png"],
    //   order: { x: 0, y: 42 },
    // },
    // {
    //   _id: "620ace6313589700166baf5a",
    //   description: "",
    //   title: "IEIÉ",
    //   subtitle: "BEBIDAS",
    //   contact: "",
    //   phone: "::::98860-8826/wa::::99979-8085",
    //   email: "",
    //   address: "Avenida Tiradentes, 130 - loja-2",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/ieieBebidas.png"],
    //   order: { x: 0, y: 43 },
    // },
    // {
    //   _id: "620ace6313589700166baf5b",
    //   description: "das 3 horas da tarde às 11 horas da noite",
    //   title: "Nogueira Lanches",
    //   subtitle: "Agradecemos a preferência",
    //   contact: "Disk Entrega:",
    //   phone: ":::32:99957-4247/:::32:3261-4764",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/nogueiraLanches.png"],
    //   order: { x: 6, y: 43 },
    // },
    // {
    //   _id: "620ace6313589700166baf5c",
    //   description:
    //     "VARIEDADES EM FERRAMENTAS, MÁQUINAS, TINTAS PARAFUSOS. TUBOS E CONEXÕES",
    //   title: "CASA RAMOS",
    //   subtitle: "Soluções para seu dia à dia",
    //   contact: "",
    //   phone: ":::32:3261-2546/wa::::98492-2747",
    //   email: "",
    //   address: "Rua Dr. João Couto, 15 - Loja 01 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/casaRamos.png"],
    //   order: { x: 0, y: 44 },
    // },
    // {
    //   _id: "620ace6313589700166baf5d",
    //   description:
    //     "COLAS, DURATEX, COMPENSADOS, PORTAS, JANELAS, FORROS, GUARNIÇÕES, TELHAS COLONIAL E AMIANTO, VERNIZES, ETC.",
    //   title: "MADEIREIRA São Geraldo",
    //   subtitle: "MADEIRAS EM GERAL",
    //   contact: "",
    //   phone: "::::3261-1977/::::3261-1662",
    //   email: "",
    //   address: "Av. Tiradentes, 298 - Centro",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/madSaoGeraldo.png"],
    //   order: { x: 6, y: 45 },
    // },
    // {
    //   _id: "620ace6313589700166baf5e",
    //   description: "A MAIOR VARIEDADE - O MELHOR PREÇO",
    //   title: "DIDI",
    //   subtitle: "MATERIAIS DE CONSTRUÇÃO",
    //   contact: "Entrega em toda Região",
    //   phone: "::::3261-1020/::::3261-1456",
    //   email: "",
    //   address: "Rua Governador Valadares, 121",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/didiMatConst.png"],
    //   order: { x: 6, y: 46 },
    // },
    // {
    //   _id: "620ace6313589700166baf5f",
    //   description:
    //     "fogões a gás, refrigeradores, microondas, ventiladores, lavadoras, liquidificadores, secador de cabelo, chuveiro elétrico, panela elétrica, chapinha de cabelo, ferro de passar roupas | SERVIÇO COM GARANTIA! ORÇAMENTO GRÁTIS! PREÇO IMBATÍVEL!",
    //   title: "LAZARO SOLUÇÕES",
    //   subtitle: "conserto de Eletrodomésticos",
    //   contact: "Ligue Já!",
    //   phone: ":::32:99932-2694/wa:::32:99946-7834",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681006",
    //   urls: ["/lazaroSolucoes.png"],
    //   order: { x: 0, y: 45 },
    // },
    // {
    //   _id: "620ace6313589700166baf5g",
    //   description: "",
    //   title: "TONHO SEGUROS",
    //   subtitle: "",
    //   contact: "",
    //   phone: ":Tonho::32:99963-5280/:Lilian::21:98035-8520/:fixo::32:3261-5232",
    //   email: "",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/tonhoSeguros.png"],
    //   order: { x: 0, y: 46 },
    // },
    // {
    //   _id: "620ace6313589700166baf5h",
    //   description:
    //     "IMPRESSÕES DE PROJETOS A0 (120x90)cm - A1 (90x60)cm - A2 (60x42)cm - A3 (42x29,7)cm",
    //   title: "ENGPAR",
    //   subtitle: "Soluções em Engenharia",
    //   contact: "",
    //   phone: "wa:::32:99943-2018",
    //   email:
    //     "fb:pauloparreirasjesus/em:eng.paulo.parreiras@gmail.com/in:eng.pauloparreiras",
    //   address: "Rua Governador Valadares, 6 - Centro",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/engparSolEng.png"],
    //   order: { x: 0, y: 47 },
    // },
    // {
    //   _id: "620ace6313589700166baf5i",
    //   description: "Especialista em Amigurumis e Tricotin",
    //   title: "Crochê da Dani",
    //   subtitle: "",
    //   contact: "Dani",
    //   phone: "wa::::99809-6092",
    //   email: "ig:@crochedadanioficial",
    //   address: "",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/crocheDaDani.png"],
    //   order: { x: 0, y: 49 },
    // },
    // {
    //   _id: "620ace6313589700166baf5j",
    //   description:
    //     "A maneira fácil de presentear sua amada mãe | Ótimos preços e muitas novidades | trabalhamos com cartão de crédito e débito",
    //   title: "LOJA SENSAÇÃO",
    //   subtitle: "PRESENTES E UTILIDADES",
    //   contact: "",
    //   phone: "wa:José Antônio:::99928-1211/wa:Regina:::99968-5358",
    //   email: "",
    //   address: "ao lado do Banco do Brasil",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "6209b62804dbe50016b07ccc",
    //   urls: ["/lojaSensacao.png"],
    //   order: { x: 0, y: 50 },
    // },
    // {
    //   _id: "620ace6313589700166baf5k",
    //   description: "MENSAL",
    //   title: "ESTACIONAMENTO TIRADENTES",
    //   subtitle: "HÁ VAGAS",
    //   contact: "",
    //   phone: "::::98898-6305/wa::::99920-3720",
    //   email: "",
    //   address:
    //     "Avenida Tiradentes, 280 - Centro - ao lado da Madeireira São Geraldo",
    //   city: "",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681008",
    //   urls: ["/estTiradentes.png"],
    //   order: { x: 0, y: 51 },
    // },
    // {
    //   _id: "620ace6313589700166baf6a",
    //   description:
    //     "Esteja visível nas redes e conquiste novos clientes - obtenha um site ou página web, para publicidade online - ARTES DIGITAL, LAYOUT, DESIGN, UX/UI | Seja visto pelos clientes em São João e Região - impulsionamento nas redes - GOOGLE ANALYTICS E OUTROS MONITORAMENTOS | Gerencie melhor seus negócios - essencial para estoques - BOM PARA MERCEARIAS, MERCADOS, DELIVERIES, HOTEIS ENTRE OUTROS | Não perca tempo com conversas interminavéis no Whatsapp - reduza confusões, seja prático e tenha agilidade - FAÇA COM QUE SEU CLIENTE PARTICIPE DA ESCOLHA E VEJA SEU CARDÁPIO ONLINE",
    //   title: "CZAR DEVS",
    //   subtitle: "",
    //   contact: "",
    //   phone: "wa:Lucas Marcus::32:99926-3905",
    //   email: "em:contato@czar.dev",
    //   address: "",
    //   city: "",
    //   link: "https://czar.dev/",
    //   qrCode: "",
    //   adFormatId: "61db2ec5b077530016af1ab0",
    //   urls: ["/czar.jpeg"],
    //   order: { x: 0, y: 52 },
    // },
    // {
    //   _id: "620ace6313589700166baf5l",
    //   description:
    //     "Artigos para festas e embalagem: Velas, pratinhos, guardanapos, caixa pizza, caixa salgados, guardanapos de balcão, copos descatáveis, bandeja para bolos, cumbuca, etc.",
    //   title: "IMPERIAL FESTAS E EMBALAGENS",
    //   subtitle: "",
    //   contact: "",
    //   phone: "wa::::99940-8834",
    //   email: "",
    //   address: "Praça Dr. Carlos Alves, 30 C - loja 5 - Centro - Beco da União",
    //   city: "São João Nepomuceno - MG",
    //   link: "",
    //   qrCode: "",
    //   adFormatId: "611872d13a1f1854a4681006",
    //   urls: ["/imperialFestas.png"],
    //   order: { x: 6, y: 39 },
    // },
  ]);
}
