// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export type AdDTO = {
  _id: string;
  description: string;
  title?: string;
  subtitle?: string;
  contact?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  link?: string;
  qrCode?: string;
  adFormatId: string;
  urls: string[];
  order: {
    x: number;
    y: number;
  };
};

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<AdDTO[]>
) {
  if (req.method === "PUT") {
    console.log(JSON.parse(req.body));
  }

  if (req.method === "POST") {
    res.status(201).json({} as AdDTO[]);
    return;
  }

  res.status(200).json([
    {
      _id: "60f1d442828335001559a296",
      description:
        "3 anos de bons serviços | Atendimento de seg. à sab. das 7 ás 18h",
      title: "Borracharia Rua Nova do José Maria Borracheiro",
      subtitle: "MAIO MÊS DE ANIVERSÁRIO",
      contact: "PRECISA DE SOCORRO É SÓ LIGAR",
      phone: "99966-9884",
      email: "",
      address: "Rua Nova - próximo ao lavador do Luciano",
      city: "São João Nepomuceno-MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/borrachariaRuaNova.png"],
      order: { x: 0, y: 0 },
    },
    {
      _id: "60f1d44c828335001559a297",
      description:
        "Toda linha de móveis, sofás, colchões, eletrodomésticos | Especialista em aprovação de crédito | Carnê até 24x com entrada para 60 dias | Entregamos em toda região",
      title: "Competição Móveis",
      subtitle: "Ta pensando em comprar seus móveis?",
      contact:
        "Fale com o Lima, atendimento personalizado e sem a necessidade de você sair de casa.",
      phone: "99954-0240",
      email: "",
      address: "Rua Coronel José Dutra, 431 - ao lado do correio",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/competicaoMoveis.png"],
      order: { x: 0, y: 1 },
    },
    {
      _id: "60f603e2557aac0015cca542",
      description:
        "com teste do sistema de injeção com Aparelho Raster - equipamento de análise e limpeza de injetores de combustivel | VENDAS DE BATERIAS, SILENCIOSO, TROCA DE ÓLEO E PEÇAS EM GERAL | Serviços em carros nacional e importado | atendimento 24 horas",
      title: "MECÂNICA E LOJA CARNEIRINHO",
      subtitle: "MECÂNICA EM GERAL",
      contact: "",
      phone: "3261-4079/99965-5864",
      email: "",
      address: "Av. Celso Cosme de Castro, 1385 - Chácara dos Palmares",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/mCarneirinho.png"],
      order: { x: 0, y: 2 },
    },
    {
      _id: "60f61fe848a9e20015ae871a",
      description:
        "Quer anunciar seu imóvel ou comprar um, me procura que eu te ajudo",
      title: "Vinícius Tim",
      subtitle: "PENSOU EM IMÓVEIS?",
      contact: "CRECI 40300",
      phone: "99910-8956",
      email: "",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/viniciusTim.png"],
      order: { x: 0, y: 3 },
    },
    {
      _id: "60f74d8b9f3e6a0015b46a5d",
      description:
        "Carvão 3 kilos 11,75 pacote | Guarana Ita 2 litros 5,99 | Biscoito a partir de 1,49 | Atum ralado Gomes da Costa 6,99 | VÁRIAS PROMOÇÕES. VENHAM CONFERIR. ESPERAM POR VOCÊS! VERÁ SERIE DE UMA CARA DE BOMEKINO",
      title: "Mercearia JM",
      subtitle: "PROMOÇÃO PARA O DIA DAS MÃES",
      contact: "Joño e a Marlene",
      phone: "99960-1502",
      email: "",
      address: "Rua Prefeito Nagib Camilo Ayupi, 448 - Bairro Caxangá",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/merceariaJM.png"],
      order: { x: 0, y: 4 },
    },
    {
      _id: "61a0273dcd24bb001686e4cd",
      description:
        "PÃO INTEGRAL, PÃO DE CENOURA, PÃO DE CEBOLA, PÃO DE BETERRABA, PÃO DE BATATA, PÃO CEARENSE E BOLO BREVIDADE",
      title: "PADARIA Jujuba",
      subtitle: "",
      contact: "",
      phone: "99906-5630",
      email: "",
      address: "Rua Miguel Manso, 49 - Jujuba",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/padariaJujuba.png"],
      order: { x: 0, y: 5 },
    },
    {
      _id: "61b92ca6ff15c00016366596",
      description: "",
      title: "CASA DE CARNES SANTA RITA",
      subtitle: "O MELHOR PARA VOCÊ",
      contact: "AOS DOMINGOS FRANGO E CARNE ASSADA",
      phone: "3261-1952/99918-5852",
      email: "",
      address: "Rua Duque de Caxias, 49 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/casaCarnesSantaRita.png"],
      order: { x: 6, y: 5 },
    },
    {
      _id: "61bbd708823d5200164b17cc",
      description:
        "BOI, PORCO, PEIXE, FRANGO FRESCO | COMIDAS VARIADAS | A PARTIR DE 3ª FEIRA: ESPETINHOS NA BRASA / TODOS OS DIAS: frango resfriado, frango em pedaços, peixes, came fresca de boi e porco e frios em geral feijão cosido, lasanha, canelone, rondele e fricassê",
      title: "ARMAZÉM DO FRANGO / Forte Frios",
      subtitle:
        "Aos finais de semana trange assado pernil assado / AOS FINAIS DE SEMANA: CARNE E FRANGO ASSADO",
      contact: "",
      phone: "99970-8535 / 3261-7024",
      email: "",
      address:
        "Avenida Tiradentes, 200 - Centro / Rua Duque de Caxias, 119 - Centro",
      city: "São João Nepomuceno",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/armFrangoForteFrios.png"],
      order: { x: 0, y: 6 },
    },
    {
      _id: "620ace6313589700166baf4b",
      description:
        "Galão de água 20 litros - Botijão de gás - Fardo de água com gás - Fardo de água sem gás",
      title: "NELSON GÁS E ÁGUA",
      subtitle: "Aceitamos: PIX, cartão de crédito e débito.",
      contact: "Disk Entrega",
      phone: "99941-3664",
      email: "",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/nelsonGasAgua.png"],
      order: { x: 0, y: 7 },
    },
    {
      _id: "620ace6313589700166baf4c",
      description: "BOLOS - TORTAS - PAES - BISCOITOS",
      title: "Bragança",
      subtitle: "PADARIA E CONFEITARIA",
      contact: "Disk Entrega",
      phone: "3261-2750",
      email: "",
      address: "Rua Coronel José Dutra, 465",
      city: "SÃO JOÃO NEPOMUCENO - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/padariaBraganca.png"],
      order: { x: 6, y: 7 },
    },
    {
      _id: "620ace6313589700166baf4d",
      description: "",
      title: "Mercado Cebolinha",
      subtitle: "",
      contact: "Entrega em domicilio grátis | Preços Baixos",
      phone: "3261-3258",
      email: "",
      address: "Rua Daniel Sarmento, 131",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/mercCebolinha.png"],
      order: { x: 0, y: 8 },
    },
    {
      _id: "620ace6313589700166baf3d",
      description: "",
      title: "Carlos Chagas",
      subtitle: "Laboratorio de Análises Clínicas",
      contact: "José Raimundo S. Gomes - Bioquimico Responsável CRF 7941",
      phone: "3261-2165",
      email: "",
      address: "Rua Getúlio Vargas, 12 - Centro",
      city: "SÃO JOÃO NEPOMUCENO - MINAS GERAIS",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/carlosChagas.png"],
      order: { x: 6, y: 8 },
    },
    {
      _id: "620ace6313589700166baf4e",
      description: "É FÁCIL TER O SORRISO QUE VOCÊ DESEJA!",
      title: "ODONTO Company",
      subtitle: "A MAIOR DO MUNDO E PARA VOCÊ TAMBÉM",
      contact: "agende já sua avaliação! tem sempre uma clinica perto de você",
      phone: "3261-3322/99954-5466",
      email: "",
      address: "Rua Duque de Caxias, 70",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/odontoCompany.png"],
      order: { x: 0, y: 9 },
    },
    {
      _id: "620ace6313589700166baf4f",
      description:
        "HARMONIZAÇÃO FACIAL | BOTOX | PREENCHIMENTO LABIAL | BIOESTIMULADORES | FIOS DE SUSTENTAÇÃO",
      title: "VANESSA BIAZUTTI",
      subtitle: "biomédica esteta",
      contact: "Vanessa Biazutti",
      phone: "99938-2448",
      email: "",
      address: "Rua Domingos Henriques de Gusmão, 56 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/vanessaBiazutti.png"],
      order: { x: 0, y: 10 },
    },
    {
      _id: "620ace6313589700166baf4g",
      description:
        "Funcionando todos os dias, servindo almoço e janta de Segunda a Quinta - Bom Apetite",
      title: "RESTAURANTE JANTINHA'S DELÍCIA",
      subtitle: "DESDE 2020",
      contact: "aceitamos cartões de crédito - disk entrega",
      phone: "99915-0483",
      email: "",
      address:
        "Rua Dr. João Cavalheiro - próximo ao aeroporto - Santa Terezinha",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/jantinhasDelicia.png"],
      order: { x: 0, y: 11 },
    },
    {
      _id: "620ace6313589700166baf4h",
      description:
        "Servimos a melhor muqueca e traíra sem espinha da região, carnes nobres | Venha saborear a melhor linguiça de vários sabores | Cerveja gelada, comida de qualidade, comida de qualidade, atendimento diferenciado é no CIROLA & REY DE MINAS | Servimos almoço de quarta a domingo de 11 às 15 horas e a noite funcionaremos à partir das 18 horas",
      title: "Bar e Restaurante CIROLA & REY DE MINAS",
      subtitle: "AGUARDAMOS SUA VISITA",
      contact: "servimos o melhor pão com tilápia e o famoso pão com linguiça",
      phone: "99969-8673/99844-8216",
      email: "",
      address: "Rua Carlos Pellegrini Rocha, 220 - Loja 7 (Posto Vitória)",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/basRestauranteCirolaReyDeMinas.png"],
      order: { x: 0, y: 12 },
    },
    {
      _id: "620ace6313589700166baf4i",
      description:
        "moda básica, abadás, linha hospitalar, camisas personalizadas, uniformes escolares, esportivos e profissionais",
      title: "D&M UNIFORMES",
      subtitle: "A VIDA TODA COM VOCÊ",
      contact: "",
      phone: "3261-2592",
      email: "",
      address:
        "Rua Governador Valadares, 64 - Centro (em frente à Caixa Econômica)",
      city: "São João Nepomuceno",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/D&MUniformes.png"],
      order: { x: 0, y: 14 },
    },
    {
      _id: "620ace6313589700166baf4j",
      description:
        "Reparo especializado em placa de iPhone e Android | Recuperação de aparelhos molhados (desoxidação) | Troca telas touch's | Troca de vidro | Troca de conectores de carga | Formatação/backupse em computadores e notebooks",
      title: "S.O.S CELULARES",
      subtitle: "ASSISTÊNCIA TÉCNICA ESPECIALIZADA",
      contact: "",
      phone: "99834-9375",
      email: "garcia_nicolas02",
      address: "Rua Doutor João Couto, 701 - loja 1 - Centro",
      city: "São João Nepomuceno",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/SOScelulares.png"],
      order: { x: 0, y: 16 },
    },
    {
      _id: "620ace6313589700166baf4k",
      description: "Não cobramos frete",
      title: "YAMAHA",
      subtitle: "Yamaha Motos",
      contact:
        "Vânia - Consultor de vendas / Tarcísio de Oliveira - Consultor de vendas",
      phone: "99855-2703 / 98832-2352",
      email: "",
      address: "Av. Israel Pinheiro - em frente Posto Padrão",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/yamaha.png"],
      order: { x: 0, y: 17 },
    },
    {
      _id: "620ace6313589700166baf4l",
      description:
        "PNEUS, BATERIAS, TROCA DE ÓLEO E AUTO PEÇAS - BORRACHARIA COMPLETA | SUPER TROCA DE ÓLEO | LUBRIFICANTE CARRO E MOTO",
      title: "GOLDIN",
      subtitle: "Tudo para o seu carro e moto",
      contact: "Disk",
      phone: "99838-7473",
      email: "",
      address: "Rua Cônego Reis, 256 - Centro",
      city: "SÃO JOÃO NEPOMUCENO - MG - PRÓXIMO DE VOCÊ",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/goldin.png"],
      order: { x: 0, y: 18 },
    },
    {
      _id: "620ace6313589700166baf4m",
      description:
        "Chega de mofo e infiltração! TINTAS IMPERMEABILIZADAS PARA SUA CASA TRABALHAMOS COM: Pedras Travertino - Pedras Ferro - Pedra moledo - Pedra Espanha | TEXTURAS: Pedras Cristais - Pedras Naturais - Cimento Queimado Tradicional e Perolizado. HORÁRIO DE FUNCIONAMENTO: SEGUNDA A SEXTA: 8:00 ÁS 18:00H SÁBADO: 8:00 ÁS 12:00H",
      title: "KASA DE CORES",
      subtitle: "SOLUÇÕES RESIDENCIAIS",
      contact: "",
      phone: "99937-7141",
      email: "@kasadecores",
      address: "Pátio da Fábrica, loja 05",
      city: "SÃO JOÃO NEPOMUCENO",
      link: "",
      qrCode: "",
      adFormatId: "620ad11413589700166baf4c",
      urls: ["/kasaDeCores.png"],
      order: { x: 0, y: 20 },
    },
    {
      _id: "620ace6313589700166baf4n",
      description:
        "[ALUGUEL] Kitnet: 1 quarto, cozinha, banheiro e área - Rua Carlos Stibler - R$400,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro e área - Rua Paulo Rocha R$400,00 + taxas | Kitnet: 1 quarto, cozinha, banheiro - Avenida Israel Pinheiro - R$400,00 + taxas | Apto: 2 quarto, sala, cozinha, banheiro, garagem e terraço - Rua Elton Ferreira Amorin - R$780,00 + taxas | Casa - 2 quartos, sala, cozinha, banheiro, área. (cômodos pequenos) - Rua Joaquim Cruz - R$400,00 + taxas | Casa - 2 quartos, sala, cozinha, banheiro, área equintal - Rua Carlos Stiebler - R$ 500,00 | Casa - 3 quartos, sala, cozinha, banheiro, área, garagem e terraço - Rua Joaquim Cruz - R$ 750,00 | Casa - 3 quartos, sala, cozinha, banheiro, área egaragem - Rua Coronel Ricardo Martins - R$650,00 | Casa - 3 quartos, sala, cozinha, banheiro, área, garagem e terraço - Rua Alcebiades Valente - R$750,00 | Apto 3 quartos, sala, cozinha, banheiro e área - Travessa João Goulart - R$700,00 + taxas | Loja c/ sobre loja - Rua Barão do Rio Branco - R$2500,00 + Taxas | Loja - Rua Dr. João Sarmento R$600,00 + taxas | Loja - Aliança Shopping - Pisos 1,2 e 3-Lojas de R$1077,00 ate R$2.810,00 + taxas | Loja - Rua Cavalheiro Verardo - R$ 1500,00 | Loja - Rua Coronel José Dutra (Antigo APOIO) - R$5.200,00 | Loja - Rua Péricles Mendonça (em frenteenergisa) - R$1.400,00 | Galpão - Rua Luiz Brum Sales - R$600,00 [VENDA] Lote Novo Horizonte - 1.000m² R$95.000,00 | Lote Novo Horizonte - 338m² R$75.000,00 | Lote Vivendas do Barão de 1000m², plano | Lote José M. Fam - 504m², com estruturapronta de 56m² para construir por cima | Lote Cond. Altos dos Pinheiros - lote 8, semi-plano com 201,7m² | Casa + Lote Santa Terezinha: área total de 600m² | Casa Centenário: 2 quartos, sala, banheiro, quintal com cozinha e quarto, piscina, garagem 3 carros, terraço coberto, telha galvanizada | Casa José Maria Fam: 3 quartos, sala, cozinha, banheiro, quintal, lavanderia e garagem | Casa Vivendas do Barão: 2 quartos, sala,cozinha, banheiro, garagem e área | Apto. São José: 1 a 3 quartos, sala, cozinha, banheiro, área | Apto. Centro - 3 quartos (suíte), sala, cozinha, banheiro, área, banheiro e garagem | Oportunidade para Empreendedores - Av. Israel Pinheiro em frente ao Clube Democráticos - 10.000m² com 180m de frente | Oportunidade para Empreendedores - Área Central com 6000m² com casa de 2 pavimentos | Casa Alto dos Pinheiros - Varandão, 3 quartos, sala, suite, lavabo, lavanderia, quintal grande, espaço gourmet com churrasqueira, piscina com banho, campo de futebol com 2 banhos, garagem 3 carros com banheiro.",
      title: "IMOBILIÁRIA CASA LEITE",
      subtitle:
        "ADMINISTRAÇÃO - VENDA - ADVOCACIA | Você empresta sua confiança. Nós lhe damos garantia.",
      contact: "CRECI/MG 9677 E 17.181 LTDA.",
      phone: "3261-1840/98828-4524",
      email: "@imobiliáriacasaleite",
      address: "Rua Coronel José Dutra, 487/101",
      city: "São João Nepomuceno - MG",
      link: "", //Entre em contato pelo nosso whatsapp (32)  Acesse no instagram
      qrCode: "",
      adFormatId: "620ad11413589700166baf4c",
      urls: ["/imbCasaLeite.png"],
      order: { x: 0, y: 26 },
    },
    {
      _id: "620ace6313589700166baf4o",
      description:
        "DOMINGOS E FERIADOS ABERTO ATÉ ÀS 13H | ASSADOS EM GERAL, SUÍNOS, BOVINOS, AVES, CERVEJA E REFRIGERANTES GELADOS",
      title: "AÇOUGUE & BAR São Joaquim",
      subtitle: "O melhor tira gosto é você quem escolhe!",
      contact: "Aceltamos todos os cartões de crédito. Reizinho - Disk Entrega",
      phone: "99814-1401",
      email: "",
      address: "Rua Carlos Pellegrine Rocha, 314 - Bairro Jose Maria Fam",
      city: "São João Nepomuceno",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/aBSaoJoaquim.png"],
      order: { x: 0, y: 32 },
    },
    {
      _id: "620ace6313589700166baf4p",
      description: "",
      title: "POPULAR GÁS E ÁGUA",
      subtitle: "",
      contact: "Samuel",
      phone: "99966-4955/99924-4955",
      email: "",
      address: '"Vem comigo"',
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/popularGasAgua.png"],
      order: { x: 0, y: 33 },
    },
    {
      _id: "620ace6313589700166baf4q",
      description: "",
      title: "Hortifruti e Mercado Central",
      subtitle: "ÁGUA E GÁS",
      contact: "Telefone e Whatsapp",
      phone: "98810-4021",
      email: "",
      address: 'Rua Doutor Fortes Bustamantes, 63 - "Rua do Taxi"',
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/hortifrutiCentral.png"],
      order: { x: 0, y: 34 },
    },
    {
      _id: "620ace6313589700166baf4r",
      description: "CARNE BOVINA, SUINA, AVES E LINGUIÇA",
      title: "Açougue Santa Rita",
      subtitle: "O melhor para você todos os dias",
      contact: "Direção: Geovani - Disk Entrega:",
      phone: "99801-6770/99836-4328",
      email: "",
      address: "Rua Coronel José Mendes, 355 - Próximo ao Bar do Fumaça",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/acougueSantaRita.png"],
      order: { x: 6, y: 34 },
    },
    {
      _id: "620ace6313589700166baf4s",
      description:
        "ENTREGAMOS GÁS, ÁGUA, CERVEJA, BEBIDAS EM GERAL, CHURRASQUEIRA, PICANHA, GELO, CORAÇÃO, BACON, BATATA CONGELADA, PEIXES E CARVÃO | Aceitamos cartões",
      title: "Marquinho GÁS",
      subtitle: "",
      contact: "Disk Entrega | Entrega Rápida",
      phone: "3261-1470/99952-3619",
      email: "",
      address: "Rua Capitão Brás, s/n - Centro",
      city: "SÃO JOÃO NEPOMUCENO - MG",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/marquinhoGas.png"],
      order: { x: 0, y: 35 },
    },
    {
      _id: "620ace6313589700166baf4t",
      description:
        "ACESSE O JORNAL ONLINE - futuramente com músicas, jogos e animações",
      title: "OPÇÃO",
      subtitle: "O SEU GUIA DE COMPRAS",
      contact: "",
      phone: "",
      email: "",
      address: "",
      city: "",
      link: "https://infop.czar.dev/",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/opcao.png"],
      order: { x: 0, y: 37 },
    },
    {
      _id: "620ace6313589700166baf4u",
      description:
        "Artesanato mineiro em: cerâmica, madeira, tecido, tapeçaria, sabonetes artesanais e outros",
      title: "Mãos Arteiras",
      subtitle: "",
      contact: "",
      phone: "3261-2762",
      email: "",
      address: "Rua Doutor Fortes Bustamantes, 4 - loja 2",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/maosArteiras.png"],
      order: { x: 0, y: 38 },
    },
    {
      _id: "620ace6313589700166baf4v",
      description: "",
      title: "MAJ SILK",
      subtitle: "",
      contact: "Jean",
      phone: "99959-4442",
      email: "maisilk@gmail.com",
      address: "Rua Expedicionário Garcia Lopes, 374 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/majSilk.png"],
      order: { x: 6, y: 38 },
    },
    {
      _id: "620ace6313589700166baf4x",
      description:
        "Cerveja super gelada | Caldos variados | Porções deliciosas | Mascote | Estufa com salgados e tira gostos variados",
      title: "BAR E MERCEARIA DAS PRIMAS",
      subtitle:
        "Servimos almoço todos os domingos | DE TERÇA A DOMINGO A PARTIR DAS 12 HORAS",
      contact: "",
      phone: "99957-7827",
      email: "",
      address: "Praça da Bandeira, 8 - Matriz",
      city: "São João Nepomuceno",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/barMercPrimas.png"],
      order: { x: 0, y: 41 },
    },
    {
      _id: "620ace6313589700166baf4y",
      description: "AGRADECEMOS A PREFERÊNCIA",
      title: "BARÃO LANCHES",
      subtitle: "Você merece a melhor!",
      contact: "Disk Entrega",
      phone: "99996-3853",
      email: "",
      address: "na Praça do Coronel",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/baraoLanches.png"],
      order: { x: 0, y: 39 },
    },
    {
      _id: "620ace6313589700166baf4z",
      description:
        "CEREAIS, BEBIDAS EM GERAL | FRANGO INTEIRO E PEDAÇO, GÁS O MELHOR PREÇO | ENTREGAMOS: GÁS E COMPRAS",
      title: "Chave de Ouro",
      subtitle: "Bar e Mercearia",
      contact: "Sebastião Rosa",
      phone: "99937-3616",
      email: "",
      address: "Rua Capitão Ferreira Campos, 93 - saída para Descoberto",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/barMercChaveDeOuro.png"],
      order: { x: 0, y: 40 },
    },
    {
      _id: "620ace6313589700166baf4a",
      description:
        "Cerveja gelada | Caldos | Porções diversas | Mascote, Pão com linguiça e o Extra Burguer",
      title: "Bar HORA EXTRA",
      subtitle: "PREPARANDO O MELHOR PARA VOCÊ.",
      contact: "Edinho / Patricia",
      phone: "99979-0437 / 99984-3818 / 99966-0407",
      email: "",
      address: "Praça da Bandeira, 58 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/barHoraExtra.png"],
      order: { x: 0, y: 42 },
    },
    {
      _id: "620ace6313589700166baf5a",
      description: "",
      title: "IEIÉ",
      subtitle: "BEBIDAS",
      contact: "",
      phone: "98860-8826/99979-8085",
      email: "",
      address: "Avenida Tiradentes, 130 - loja-2",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/ieieBebidas.png"],
      order: { x: 0, y: 43 },
    },
    {
      _id: "620ace6313589700166baf5b",
      description: "das 3 horas da tarde às 11 horas da noite",
      title: "Nogueira Lanches",
      subtitle: "Agradecemos a preferência",
      contact: "Disk Entrega:",
      phone: "99957-4247/3261-4764",
      email: "",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/nogueiraLanches.png"],
      order: { x: 6, y: 43 },
    },
    {
      _id: "620ace6313589700166baf5c",
      description:
        "VARIEDADES EM FERRAMENTAS, MÁQUINAS, TINTAS PARAFUSOS. TUBOS E CONEXÕES",
      title: "CASA RAMOS",
      subtitle: "Soluções para seu dia à dia",
      contact: "",
      phone: "3261-2546/98492-2747",
      email: "",
      address: "Rua Dr. João Couto, 15 - Loja 01 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/casaRamos.png"],
      order: { x: 0, y: 44 },
    },
    {
      _id: "620ace6313589700166baf5d",
      description:
        "COLAS, DURATEX, COMPENSADOS, PORTAS, JANELAS, FORROS, GUARNIÇÕES, TELHAS COLONIAL E AMIANTO, VERNIZES, ETC.",
      title: "MADEIREIRA São Geraldo",
      subtitle: "MADEIRAS EM GERAL",
      contact: "",
      phone: "3261-1977 / 3261-1662",
      email: "",
      address: "Av. Tiradentes, 298 - Centro",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/madSaoGeraldo.png"],
      order: { x: 6, y: 45 },
    },
    {
      _id: "620ace6313589700166baf5e",
      description: "A MAIOR VARIEDADE - O MELHOR PREÇO",
      title: "DIDI",
      subtitle: "MATERIAIS DE CONSTRUÇÃO",
      contact: "Entrega em toda Região",
      phone: "3261-1020/3261-1456",
      email: "",
      address: "Rua Governador Valadares, 121",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/didiMatConst.png"],
      order: { x: 6, y: 46 },
    },
    {
      _id: "620ace6313589700166baf5f",
      description:
        "fogões a gás, refrigeradores, microondas, ventiladores, lavadoras, liquidificadores, secador de cabelo, chuveiro elétrico, panela elétrica, chapinha de cabelo, ferro de passar roupas | SERVIÇO COM GARANTIA! ORÇAMENTO GRÁTIS! PREÇO IMBATÍVEL!",
      title: "LAZARO SOLUÇÕES",
      subtitle: "conserto de Eletrodomésticos",
      contact: "Ligue Já!",
      phone: "99932-2694/99946-7834",
      email: "",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681006",
      urls: ["/lazaroSolucoes.png"],
      order: { x: 0, y: 45 },
    },
    {
      _id: "620ace6313589700166baf5g",
      description: "",
      title: "TONHO SEGUROS",
      subtitle: "",
      contact: "Tonho (32) / Lilian (21) / fixo (32)",
      phone: "99963-5280/98035-8520/3261-5232",
      email: "",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/tonhoSeguros.png"],
      order: { x: 0, y: 46 },
    },
    {
      _id: "620ace6313589700166baf5h",
      description:
        "IMPRESSÕES DE PROJETOS AO (120x90)cm A1 (90x60)cm A2 (60x42)cm A3 (42x29,7)cm",
      title: "ENGPAR",
      subtitle: "Soluções em Engenharia",
      contact: "",
      phone: "99943-2018",
      email:
        "pauloparreirasjesus / eng.paulo.parreiras@gmail.com / eng.pauloparreiras",
      address: "Rua Governador Valadares, 6 - Centro",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/engparSolEng.png"],
      order: { x: 0, y: 47 },
    },
    {
      _id: "620ace6313589700166baf5i",
      description: "Especialista em Amigurumis e Tricotin",
      title: "Crochê da Dani",
      subtitle: "",
      contact: "Dani",
      phone: "99809-6092",
      email: "@crochedadanioficial",
      address: "",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/crocheDaDani.png"],
      order: { x: 0, y: 49 },
    },
    {
      _id: "620ace6313589700166baf5j",
      description:
        "A maneira fácil de presentear sua amada mãe | Ótimos preços e muitas novidades | trabalhamos com cartão de crédito e débito",
      title: "LOJA SENSAÇÃO",
      subtitle: "PRESENTES E UTILIDADES",
      contact: "José Antônio / Regina",
      phone: "99928-1211/99968-5358",
      email: "",
      address: "ao lado do Banco do Brasil",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "6209b62804dbe50016b07ccc",
      urls: ["/lojaSensacao.png"],
      order: { x: 0, y: 50 },
    },
    {
      _id: "620ace6313589700166baf5k",
      description: "MENSAL",
      title: "ESTACIONAMENTO TIRADENTES",
      subtitle: "HÁ VAGAS",
      contact: "",
      phone: "98898-6305/99920-3720",
      email: "",
      address:
        "Avenida Tiradentes, 280 - Centro - ao lado da Madeireira São Geraldo",
      city: "",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681008",
      urls: ["/estTiradentes.png"],
      order: { x: 0, y: 51 },
    },
    {
      _id: "620ace6313589700166baf6a",
      description:
        "Esteja visível nas redes e conquiste novos clientes - obtenha um site ou página web, para publicidade online - ARTES DIGITAL, LAYOUT, DESIGN, UX/UI | Seja visto pelos clientes em São João e Região - impulsionamento nas redes - GOOGLE ANALYTICS E OUTROS MONITORAMENTOS | Gerencie melhor seus negócios - essencial para estoques - BOM PARA MERCEARIAS, MERCADOS, DELIVERIES, HOTEIS ENTRE OUTROS | Não perca tempo com conversas interminavéis no Whatsapp - reduza confusões, seja prático e tenha agilidade - FAÇA COM QUE SEU CLIENTE PARTICIPE DA ESCOLHA E VEJA SEU CARDÁPIO ONLINE",
      title: "CZAR DEVS",
      subtitle: "",
      contact: "Lucas Marcus",
      phone: "99926-3905",
      email: "contato@czar.dev",
      address: "",
      city: "",
      link: "https://czar.dev/",
      qrCode: "",
      adFormatId: "61db2ec5b077530016af1ab0",
      urls: ["/czar.jpeg"],
      order: { x: 0, y: 52 },
    },
    {
      _id: "620ace6313589700166baf5l",
      description:
        "Artigos para festas e embalagem: Velas, pratinhos, guardanapos, caixa pizza, caixa salgados, guardanapos de balcão, copos descatáveis, bandeja para bolos, cumbuca, etc.",
      title: "IMPERIAL FESTAS E EMBALAGENS",
      subtitle: "",
      contact: "",
      phone: "99940-8834",
      email: "",
      address: "Praça Dr. Carlos Alves, 30 C - loja 5 - Centro - Beco da União",
      city: "São João Nepomuceno - MG",
      link: "",
      qrCode: "",
      adFormatId: "611872d13a1f1854a4681006",
      urls: ["/imperialFestas.png"],
      order: { x: 6, y: 39 },
    },
  ]);
}
